### PR TITLE
#3044. Time series autotranslation bug

### PR DESCRIPTION
**Pull request by maxyeg**
I found that autotranslation in JS ruins DataTable with complex(object) key.
Here: `o[v.values[r][0]] =` index is an object with type=Date and timestamp field. As it converted to string as `[object object]` all values will be mapped to this key and we can see:
[object object] 0.1234123123

Confirm if that's what we need, please.

### CODE REVIEW

**Comment by scottdraves** [comment]
this is a step in the right direction but more is needed to fix it for R.

**Comment by scottdraves** [comment]
:+1:

**Comment by maxyeg** [comment]
I've fixed this in R now. But as now values are put under integer key(timestamp) in javascript - it changes original value.
You can add python3 cell with code: `beaker.ts` and see that value in the first column differs from initial value.

**Comment by scottdraves** [comment]
:+1:

**Pull request merged**
