### PR TITLE
#5813 move js dir to top

### PR DESCRIPTION
**Pull request by rbidas**

### CODE REVIEW

**Comment by benmccann** [comment]
@rbidas needs a rebase now

**Comment by scottdraves** [comment]
this conflicts with the widget branches and it's pretty simple so let's put this on hold.

**Comment by scottdraves** [comment]
OK time to bring this back to life.
Please bring up to date with master (or just recreate).
The difference is now there are 2 js directories, js and jslab, so
move them to js/notebook and js/lab.
cc @mjurowicz-xsolve @jmsdnns

**Comment by scottdraves** [comment]
replaced by https://github.com/twosigma/beakerx/pull/6446

**Pull request closed without merging**
