### PR TITLE
jarek/4901_2: remove duplicated jars

### PR DESCRIPTION
**Pull request by jaroslawmalekcodete**

### CODE REVIEW

**Comment by jaroslawmalekcodete** [comment]
kick jenkins

**Comment by jaroslawmalekcodete** [comment]
kick jenkins

**Comment by scottdraves** [comment]
needs testing on windows and mac.

**Comment by scottdraves** [comment]
confirmed on mac 👍

**Comment by konstantinTarletski** [comment]
1. by gradle build and then check if beaker works  --- OK
2. the same for distribution  --- OK
3. the same for electron version  --- OK
4. the same for docker version --- CAN`T TEST

**Comment by EfimovVladimir** [comment]
confirmed on Docker :+1:

**Pull request merged**
