### PR TITLE
#6423 port port BeakerX tree panel to Lab

### PR DESCRIPTION
**Pull request by piorek**
image

### CODE REVIEW

**Comment by scottdraves** [comment]
cool, works well in Lab.
can you just change the name under which its listed from "BeakerX - Tree" to "BeakerX Options"?

**Comment by piorek** [comment]
> can you just change the name under which its listed from "BeakerX - Tree" to "BeakerX Options"?

changed

**Comment by scottdraves** [comment]
awesome, works great in nb and lab :)

one glitch: put a number in the heap field, like 10.  let it sync.
then click on the field and hit backspace twice.  let it sync.
i get a NaN in the preview line
screen shot 2018-02-01 at 10 28 11 pm

**Comment by piorek** [comment]
fixed

**Pull request merged**
