### PR TITLE
allow deleting recent notebooks #3855

### PR DESCRIPTION
**Pull request by kpaharelau**
Done

### CODE REVIEW

**Comment by scottdraves** [comment]
cool thanks, please make these changes
1) vertically center the X within the item.
2) do not underline on mouseover.
3) do not prompt, just delete.

**Comment by scottdraves** [comment]
4) add a tooltip, if you hover it should say "click to remove from history"

**Comment by scottdraves** [comment]
color of x should be #ccc not #333

**Comment by kpaharelau** [comment]
is it correct colors?
image
image

**Pull request merged**
