### PR TITLE
Fix empty cell when result is null. Fix #5204

### LINKED ISSUE #5204: duplicate fn call
https://github.com/twosigma/beakerx/blob/master/kernel/base/src/main/java/com/twosigma/beaker/jupyter/msg/MessageCreator.java#L166

found by @hadim

### PR DESCRIPTION
**Pull request by hadim**
Ping @scottdraves 

Now it works for me.

### CODE REVIEW

**Comment by hadim** [comment]
Except that now `gradle test` fails : 

```
com.twosigma.beaker.jupyter.msg.MessageCreatorTest > createMessageWithNullResult_shouldReturnNullStringForNull FAILED
    java.lang.NullPointerException at MessageCreatorTest.java:53

713 tests completed, 1 failed
:kernel:base:test FAILED
:kernel:base:jacocoTestReport

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kernel:base:test'.
> There were failing tests. See the report at: file:///home/hadim/Insync/Documents/Code/postdoc/beakerx/kernel/base/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

I don't know how you want to handle that.

**Comment by hadim** [comment]
I fixed the test.

**Comment by scottdraves** [comment]
this makes null a non-printing result which isn't something we want to do, since we have OutputCell.HIDDEN for that.

**Comment by hadim** [comment]
Ok I see. I'll let you fix it then.

**Comment by hadim** [comment]
Hi @scottdraves , are you still planning to fix this ?

**Comment by scottdraves** [comment]
hi not sure what you mean -- OutputCell.HIDDEN works and widgets return it.
and that duplicate fn call was also fixed.  am i missing something?

**Comment by hadim** [comment]
When the returned object is `null`, jupyter console or notebook display `null`. I am not using any widget on the Jupyter client side. 

Is this OutputCell.HIDDEN beakerx specific or Jupyter specific ?

**Comment by scottdraves** [comment]
> object is null, jupyter console or notebook display null

This is by design.  I know it does not really match Python behavior, and I can see doing it either way, but my understanding is the users prefer to see it.

`OutputCell.HIDDEN` is BeakerX specific.  I would not mind having that value available by a better/shorter name as well as this legacy name.

**Comment by hadim** [comment]
Oh, I see now.

Well, I don't really like to see that value returned but if you think the opposite maybe it's possible to make this behavior configurable?

What do you think ?

**Comment by scottdraves** [comment]
I think if we do https://github.com/twosigma/beakerx/issues/5120 right then the user should be able to configure a repr for null be it "null", empty output, or whatever :)

even if it does not fall out of that i think it's a good idea i filed an issue for it.

**Comment by hadim** [comment]
Ok perfect. Thanks.

**Pull request closed without merging**
