### PR TITLE
plot hover circle inconsistent #3025

### PR DESCRIPTION
**Pull request by kpaharelau**
1. Removing drawing circle for line. Do the bold line, like when you hover over the legend
2. Change algorithm for getting  coordinates of  target point for the pinned tooltip line
   a. Use center for bars and heatmap
   b. use mouse position for a steam
   This is bug is correlated to https://github.com/twosigma/beaker-notebook/issues/3250.
3. Filter svgfilter did not work - fixed

Use      https://www.dropbox.com/s/yltwp4rk6nrclwa/3025.bkr?dl=0
for testing new behaviour

### CODE REVIEW

**Comment by scottdraves** [comment]
OK this is a step in the right direction, i don't get tips without lines anymore :)

but there are some problems.
when you highlight an item on mouseover, it should just highlight the individual point or or line segment, not the whole series.
i am not seeing points getting highlighted.
the highlight does not seem as fat as when i use the legend.

also, it seems inconsistent to sometimes use the clicked location like for stems, and sometimes use the center.  i think always using the actual clicked location is better.

**Comment by kpaharelau** [comment]
example why using the clicked location is not good solution by my opinion

image

you can use https://www.dropbox.com/s/yltwp4rk6nrclwa/3025.bkr?dl=0
for the tests

**Comment by kpaharelau** [comment]
this is also fix for
https://github.com/twosigma/beaker-notebook/issues/3250
https://github.com/twosigma/beaker-notebook/issues/3243

**Comment by scottdraves** [comment]
i don't see what you mean about the problem with using the clicked location.
the image above looks fine.  what's the problem?

also still missing: the item you are hovered over should highlight (get fatter).
similar to the legend, if you move the mouse quickly over the item it should not respond.
this is true of the tooltip in general.

**Comment by scottdraves** [comment]
:+1:

**Comment by scottdraves** [comment]
kick jenkins

**Pull request merged**
