### PR TITLE
PR for renaming com.twosigma.beaker to com.twosigma.beakerx

### PR DESCRIPTION
**Pull request by konstantinTarletski**

### CODE REVIEW

**Comment by scottdraves** [comment]
it compiles that's good but when i create a new groovy notebook i get:
```
Error: Could not find or load main class com.twosigma.beaker.groovy.GroovyKernel
[I 18:46:00.411 NotebookApp] KernelRestarter: restarting kernel (2/5)
Error: Could not find or load main class com.twosigma.beaker.groovy.GroovyKernel
[I 18:46:03.419 NotebookApp] KernelRestarter: restarting kernel (3/5)
Error: Could not find or load main class com.twosigma.beaker.groovy.GroovyKernel
[W 18:46:04.481 NotebookApp] Timeout waiting for kernel_info reply from d2f2343b-d712-4b03-b83a-b91773bc9232
[I 18:46:06.425 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel d2f2343b-d712-4b03-b83a-b91773bc9232 restarted
Error: Could not find or load main class com.twosigma.beaker.groovy.GroovyKernel
[W 18:46:09.435 NotebookApp] KernelRestarter: restart failed
```

**Comment by konstantinTarletski** [comment]
Fixed :
Groovy
Java
Scala
Clojure

**Comment by scottdraves** [comment]
@hadim this will impact you

**Comment by hadim** [comment]
Ok!

**Pull request merged**
