### PR TITLE
Add new menu buttons

### PR DESCRIPTION
**Pull request by samccone**
@scottdraves let me know what you think of this, I want to tweak the implementation a bit more but I wanted to get your thoughts on this first :)

finishes #1799

screen shot 2015-08-03 at 5 31 28 pm
screen shot 2015-08-03 at 5 31 24 pm
screen shot 2015-08-03 at 5 31 20 pm

### CODE REVIEW

**Comment by scottdraves** [comment]
Hey sam this looks great, can you try:
- [x] make them as thin as possible vertically, ideally the same height as they are now.  Use all lowercase to save some height.
- [x] add the word "code" to the code menu, keep the triangle on the right side.
- [x] add the triangle to the section menu.
- [x] increase the horiz space between them, and make them all the same.
- [x] change H1/H2/H3/H4 items to read "Level 1" "Level 2" etc.
- [x] i am seeing some weird behavior if i open a menu and then mouse-over a different cell, the old buttons vanish and the new ones appear (good) but the new menu is open.  this is different from the old buttons and kind of annoying.
- [x] the final big insert button should match.

**Comment by scottdraves** [comment]
screen shot 2015-08-04 at 3 40 59 pm

**Comment by scottdraves** [comment]
still not thin like they were, text is different sizes, vertical alignment off.

**Comment by samccone** [comment]
screen shot 2015-08-04 at 4 46 50 pm
screen shot 2015-08-04 at 4 46 47 pm
screen shot 2015-08-04 at 4 46 40 pm

**Comment by scottdraves** [comment]
nice buttons but we can't increase the spacing between cells!

**Pull request merged**
