### PR TITLE
Function arguments list/help #1501. Help for IPython

### PR DESCRIPTION
**Pull request by mnavasiolava**
Use shift-tab to call help.
Works only for python3

### CODE REVIEW

**Comment by scottdraves** [comment]
looks great.
should open on control-shift-space also.
should work with python3 too.
if you continue typing into the codemirror (or press ESC) the help window should close.

**Comment by mnavasiolava** [comment]
all items are fixed

**Comment by scottdraves** [comment]
:+1:

**Comment by ildipo** [comment]
We need a rebase on this PR

**Pull request merged**
