### PR TITLE
#Fix for missmatch argument in tablesaw.

### PR DESCRIPTION
**Pull request by michalgce**

### CODE REVIEW

**Comment by benmccann** [comment]
Were you getting an error? The current checked in code was working for me

**Comment by michalgce** [comment]
image

**Comment by benmccann** [comment]
Hmm. Strange. Here's what I get. Are you sure you're running the latest version of beakerx?

screenshot from 2017-11-10 22-07-22

**Comment by scottdraves** [comment]
decided to remove the cause https://github.com/twosigma/beakerx/pull/6306

**Pull request closed without merging**
