### PR TITLE
#6688 dark theme

### PR DESCRIPTION
**Pull request by piorek**
- [x] menus in plot and data grid
- [x] Data grids styles after sorting
- [x] spark ui style after connecting (alignment is off)
- [x] plot text item color (black text and arrows)
- [x] resize thumb missing in plots

### CODE REVIEW

**Comment by scottdraves** [comment]
this loses the fonts?

**Comment by piorek** [comment]
probably incorrectly resolved merge conflict. Its ok now.

**Comment by scottdraves** [comment]
This is looking good but I found a few crashes.  In PlotFeatures.ipynb, the Text cell crashes with:
```
index.js:12319 Uncaught (in promise) TypeError: Cannot read property 'substr' of undefined
    at Object.createColor (index.js:12319)
    at r.format (index.js:80390)
    at new r (index.js:80382)
    at Object.createPlotItem (index.js:50529)
    at Object.formatModel (index.js:50285)
    at Object.standardizeModel (index.js:49942)
    at M.standardizeData (index.js:37430)
    at M.init (index.js:37516)
    at initStandardPlot (index.js:64851)
    at index.js:64756
```
the main Charting.ipynb example fails the same way.

and the `%%spark` magic crashes with:
```
java.lang.RuntimeException: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
```

**Comment by piorek** [comment]
I'm not able to reproduce those errors

**Comment by scottdraves** [comment]
spark magic crash does not appear on my other machine,
but the substr of undefined problem looks real.
please work with LM tomorrow to straighten it out.

**Pull request merged**
