### PR TITLE
windows version leaves nginx dir #3398

### PR DESCRIPTION
**Pull request by kpaharelau**
I found that  org.apache.cxf.helpers.FileUtils.delete method works fine.

Electron application on the Windows platform has big problem. We use 'taskkill' command for a java process stopping. In this case java application doesn't receive any signals and ShootdownHook doesn't work.  I have used communication across console output. Idea is very strange but it is works

### CODE REVIEW

**Comment by scottdraves** [comment]
thanks cit but i agree, it seems pretty hacky.
is there a way to send a message to the server to exit instead of task kill?
about a rest call to exit?

**Comment by kpaharelau** [comment]
I think solution is a service that returns list of temporary folders for delete

**Comment by scottdraves** [comment]
kick jenkins

**Comment by scottdraves** [comment]
worked on mac but still left an nginx dir on linux.

**Pull request merged**
