### PR TITLE
Fix language indicators on cells

### LINKED ISSUE #443: Show language plugin indicator on code cells in 'Advanced mode'
In Advanced mode, right now there is no easy way to tell which language was used for a particular code cell.

### LINKED ISSUE #553: In advanced mode, you can’t tell what language a cell is
(V1, GH#443) (Ang has already done some work on this)

### LINKED ISSUE #599: element badge and language name stacked over cell, instead of L to R
screen shot 2014-09-09 at 7 55 44 pm

### PR DESCRIPTION
**Pull request by samccone**
fixes #599
fixes #553
fixes #443

### CODE REVIEW

**Comment by anglee** [comment]
The code change looks good.
Here are the screen shots of the result of this change. @melmac48 please comment if they are ok.

# Regular mode

image

# Advanced mode

image

**Comment by samccone** [comment]
:dancer: :dancer: :dancer: :dancer: 

:fire: to the rest of p1!!

**Comment by melmac48** [comment]
They're fine for now. The original design for Advanced mode had them on the right, next to the hamburger menu but for v1 this should be okay.

**Comment by melmac48** [comment]
Sam, if you get a chance can you reevaluate this and if it's not too difficult, make it look like:

image

**Comment by scottdraves** [comment]
before you do that can we consider bringing the other icons back in
advanced mode.
unclear to me why they would not be there.... ???

On Wed, Sep 10, 2014 at 8:28 PM, Mel MacMahon notifications@github.com
wrote:

> Sam, if you get a chance can you reevaluate this and if it's not too
> difficult, make it look like:
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/5270779/4227699/85522e54-394a-11e4-9ecd-1d2485bd0236.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/twosigma/beaker-notebook/pull/611#issuecomment-55204084
> .

## 

ScottDraves.com http://www.ScottDraves.com
google.com/+ScottDraves

**Comment by melmac48** [comment]
so based on the initial designs, the belief was that there was too much whitespace in regular mode, so we created an advanced mode. The menu items in basic mode take up a row of the space in the cell where as the hamburger menu doesn't, instead it takes up a column - it's on the same line as the first line of code in the cell.. adding the language icon increases the size of the column (which can't have code in it). I think this is okay, but adding all the icons would make this column really big. At least that's my understanding of the issue. Also, the belief is that in advanced mode people are using hotkeys for actions, so don't need menu shortcuts (not sure if all the short cuts have hot keys implemented yet though).

**Comment by scottdraves** [comment]
OK agreed we cannot increase vertical whitespace.
but there are no hotkeys for these actions.
and hotkeys are much much harder than icons.
there's room for the element badge on the left, why can't there be room for
these on the right?
the mode is unusable as it stands.

On Wed, Sep 10, 2014 at 8:46 PM, Mel MacMahon notifications@github.com
wrote:

> so based on the initial designs, the belief was that there was too much
> whitespace in regular mode, so we created an advanced mode. The menu items
> in basic mode take up a row of the space in the cell where as the hamburger
> menu doesn't, instead it takes up a column - it's on the same line as the
> first line of code in the cell.. adding the language icon increases the
> size of the column (which can't have code in it). I think this is okay, but
> adding all the icons would make this column really big. At least that's my
> understanding of the issue. Also, the belief is that in advanced mode
> people are using hotkeys for actions, so don't need menu shortcuts (not
> sure if all the short cuts have hot keys implemented yet though).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/twosigma/beaker-notebook/pull/611#issuecomment-55205272
> .

## 

ScottDraves.com http://www.ScottDraves.com
google.com/+ScottDraves

**Comment by melmac48** [comment]
because the way it's implemented right now the icons are flush up against the top border and it doesn't look good. we can discuss it further tomorrow.

**Pull request merged**
