### PR TITLE
Harden failing specs

### PR DESCRIPTION
**Pull request by samccone**

### CODE REVIEW

**Comment by samccone** [comment]
welp it looks like this fixes two of the issues

**Comment by scottdraves** [comment]
ang pointed out: this should also remove use of JS cell in the default notebook which was also removed.

**Comment by samccone** [comment]
:+1: on it

**Comment by samccone** [comment]
oh it passes

**Comment by samccone** [comment]
:dancer: :dancer: :dancer: :dancer: :dancer: :dancer: :dancer: :dancer: :dancer:

**Pull request merged**
