### PR TITLE
Remove goto button and update tests

### LINKED ISSUE #496: Remove goto button on dashboard and make the entire notebook row clickable

### PR DESCRIPTION
**Pull request by samccone**
Fixes #496

### CODE REVIEW

**Comment by samccone** [comment]
Looks like we are getting a timeout waiting for the python eval to load

**Comment by anglee** [comment]
Looks like this change made only the notebook title (Text) part clickable, but not the entire row as #496 describes. @samccone or @melmac48, please confirm what the expected behavior should be.

**Comment by samccone** [comment]
I thought this is what we wanted, but i guess the final call is @melmac48

**Comment by melmac48** [comment]
If only the notebook text and button are clickable, then this is good for now, thanks.

**Comment by anglee** [comment]
The goto button has been removed

**Comment by melmac48** [comment]
Okay, that's fine.

**Pull request merged**
