### PR TITLE
jarek/8056: separate table display v2

### PR DESCRIPTION
**Pull request by jaroslawmalekcodete**

### CODE REVIEW

**Comment by EfimovVladimir** [comment]
see http://localhost:8888/notebooks/test/ipynb/clojure/ClojureTest.ipynb 
image

**Comment by EfimovVladimir** [comment]
see http://localhost:8888/notebooks/test/ipynb/clojure/InfiniteLoopClojureTest.ipynb
we can't interrupt infinite loop

**Comment by EfimovVladimir** [comment]
error: `java.lang.RuntimeException: java.lang.RuntimeException: org.apache.http.conn.HttpHostConnectException`
see http://localhost:8888/notebooks/doc/groovy/AutoTranslation.ipynb
image
http://localhost:8888/notebooks/doc/groovy/GeneralAutotranslation.ipynb
image


it was fixed

**Comment by jaroslawmalekcodete** [comment]
> see http://localhost:8888/notebooks/test/ipynb/clojure/ClojureTest.ipynb
> image

**Comment by jaroslawmalekcodete** [comment]
> see http://localhost:8888/notebooks/test/ipynb/clojure/ClojureTest.ipynb
> image

it looks like the issue was fixed in https://github.com/twosigma/beakerx/pull/8066/commits/000d9a75b6bb98830c852fb709712f8d27171f03
plsease try to test it again

**Comment by EfimovVladimir** [comment]
> see http://localhost:8888/notebooks/test/ipynb/clojure/ClojureTest.ipynb
> image

was fixed

**Comment by EfimovVladimir** [comment]
> see http://localhost:8888/notebooks/test/ipynb/clojure/InfiniteLoopClojureTest.ipynb
> we can't interrupt infinite loop

was fixed

**Comment by EfimovVladimir** [comment]
see http://localhost:8888/notebooks/doc/python/ChartingAPI.ipynb
text elements don't work:
image

it was fixed

**Comment by EfimovVladimir** [comment]
classic notebook and lab works good now

**Comment by EfimovVladimir** [comment]
conda package of `tabledisplay` was installed and looks good (windows and ubuntu)

**Pull request merged**
