### PR TITLE
Extra scrolls on table when changing beaker theme #3860

### PR DESCRIPTION
**Pull request by mnavasiolava**

### CODE REVIEW

**Comment by scottdraves** [comment]
:+1:

**Comment by scottdraves** [comment]
kick jenkins

**Comment by mnavasiolava** [comment]
kick jenkins

**Comment by scottdraves** [comment]
kick jenkins

**Comment by scottdraves** [comment]
bring up to date with master please

**Comment by mnavasiolava** [comment]
done

**Pull request merged**
