### PR TITLE
Replace epiceditor with straight marked.js

### PR DESCRIPTION
**Pull request by buob**

### CODE REVIEW

**Comment by samccone** [comment]
:clap: :clap: :clap:

**Comment by scottdraves** [comment]
when you click on the cell, a caret does not appear and i cannot type.  i have to click again.

**Comment by scottdraves** [comment]
clicking away does not format as md

**Comment by scottdraves** [comment]
rm -r core/src/vendor/epiceditor

**Comment by scottdraves** [comment]
when you first create the cell and it is empty, and then you click on it to edit it, it expands vertically.

**Comment by buob** [comment]
Updated per comments :muscle:

**Comment by scottdraves** [comment]
:dolphin:

**Pull request merged**
