### PR TITLE
#6611 easyform radio buttons bad default value

### PR DESCRIPTION
**Pull request by piorek**

### CODE REVIEW

**Comment by piorek** [comment]
I had to introduce beakerx RadioButtons, and made corresponding  changest in java and python files, but now I think its purely backend issue.

in **pyton** notebook i can do:
```py
from beakerx import *
g = EasyForm("Field Types")
options = ["a", "b", "c", "d"]
g.addRadioButtons("Radio Buttons", options)
g["Radio Buttons"] = "a"
g
```
`"a"` option of radio is selected as expected
and then 
```py
g["Radio Buttons"] = None
```
no option of radio is selected

----

I've tried to do the same in **groovy**:
```java
g = new EasyForm("Field Types")
options = ["a", "b", "c", "d"]
g.addRadioButtons("Radio Buttons", options)
g["Radio Buttons"] = "a"
g
```
`"a"` option of radio is selected
but when I've tried to unselect radio options by 
``` java
g["Radio Buttons"] = null
```
nothing happens (i tried with `""` as well)

----

I believe that this is caused by java implementation of **SelectionWidget**.
`defaultIndex` is 0 and therefore it is not possible to select nothing

If that will be fixed overwriting `render()` method in js/notebook/src/easyForm/radioButtonsWidget.ts
probably won't be needed.

**Comment by scottdraves** [comment]
Sorry I don't understand why we can't use the std radio button widget, can you explain please?

**Comment by scottdraves** [comment]
I think you are right about groovy not being able to clear with null.  @lmitusinski can you please push a commit to fix that?

**Comment by piorek** [comment]
After fix in java, std radio widget will be ok.

I had to introduce RadioButtonsView and RadioButtonsModel in `ts` to overwrite render method. When I did that I had to make corresponding changes on the `java` and `python` files.

While making those changes I realized that implementation differs and its not an issue to fix on front.

**Comment by piorek** [comment]
The difference between python and java is the initial state of radio widget after creation:

**pyhon** 
index: None value: None
**java** 
index: 0, value: 1st option

**Comment by piorek** [comment]
Cleaned PR, tested on python and groovy kernel

**Pull request merged**
