### PR TITLE
customizing tool tips and item labels #3372

### PR DESCRIPTION
**Pull request by kpaharelau**
use for testing
https://www.dropbox.com/s/p9fwlx3uqlm0xhs/3372.bkr?dl=0

### CODE REVIEW

**Comment by scottdraves** [comment]
the tooltips look great, but the itemLabel option should set the item labels, right now it is setting the tooltips.  it should also turn on showItemLabel automatically.

**Comment by scottdraves** [comment]
also please add your test notebook to the tutorial directory and link to it from the main tutorial.

**Comment by kpaharelau** [comment]
image

image

**Comment by scottdraves** [comment]
:+1:

**Pull request merged**
