### PR TITLE
Show Column menu item with many columns #3723

### PR DESCRIPTION
**Pull request by mnavasiolava**

### CODE REVIEW

**Comment by scottdraves** [comment]
if you should still use as much vertical space as possible.
screen shot 2016-04-22 at 10 09 43 am

**Comment by mnavasiolava** [comment]
submenu scroll appears only if submenu exceeds the bottom of the screen. 
search box appears if there are more than 10 items in submenu

**Comment by mnavasiolava** [comment]
at least 10 submenu items are shown on the screen

**Comment by scottdraves** [comment]
:+1:

**Pull request merged**
