### PR TITLE
initial notebook tests

### PR DESCRIPTION
**Pull request by samccone**

### CODE REVIEW

**Comment by samccone** [comment]
@scottdraves Is there anything else you would like to see on this PR before merge?

**Comment by anglee** [comment]
@samccone, could you please create a wiki page, if there isn't one yet, about dill and how to run tests?

**Comment by samccone** [comment]
sure thing @anglee

**Comment by samccone** [comment]
so I have docs here
https://github.com/twosigma/beaker-notebook/blob/master/test/README.md

But I will also add a link in the wiki

**Pull request merged**
