### PR TITLE
jarek/4938: upgrade to jetty9

### PR DESCRIPTION
**Pull request by jaroslawmalekcodete**

### CODE REVIEW

**Comment by scottdraves** [comment]
great, looks good so far but i need to test it more.

**Comment by scottdraves** [comment]
possible to use jetty v9.3.13.v20161014 instead of v9.3.6.v20151106?

**Comment by scottdraves** [comment]
so far so good :) still testing....

**Comment by jaroslawmalekcodete** [comment]
kick jenkins

**Comment by scottdraves** [comment]
closing all PRs and issues in big switch to BeakerX.

**Pull request closed without merging**
