### PR TITLE
Add top-level gradle build file that just redirects to our existing buil...

### PR DESCRIPTION
**Pull request by scottdraves**
...d system.  This addresses part of Issue #316, enough to get working with Travis.  Also add a .travis.yml file that should get us building there.

### CODE REVIEW

**Comment by anglee** [comment]
So is the build script in core/config/builds deprecated now?

**Comment by scottdraves** [comment]
no i just made the root redirect there as a quick fix.

**Comment by scottdraves** [comment]
but yes, after this goes in i will simplify the documentation now that cd down there is not necessary.

**Comment by anglee** [comment]
OK. This is fine, given the benefit from integration with travis.

I do want to point out the original design was there to make repositories separation trivial.

And yes, please get rid of core/config/builds scripts soon, otherwise, we need docs or comments in files to ensure they are sync'ed when developers touch them

**Pull request closed without merging**
