### PR TITLE
Bug Fixes

### PR DESCRIPTION
**Pull request by buob**

### CODE REVIEW

**Comment by scottdraves** [comment]
what is the change to gulpfile?

**Comment by buob** [comment]
It's just an added utility so devs can run `gulp` and it compiles and watches.

@samccone no, partial revert of larger feature.

**Comment by scottdraves** [comment]
sorry i don't understand, gulp already runs to compile the files....
what does this change do?

**Comment by buob** [comment]
It's just a shorthand.  Before this commit, the dev process was `gulp compile --debug` then `gulp watch`.  This just adds a "default task", which means a developer can only run `gulp` and it will do those things, because that's more or less the default manual task.

**Comment by scottdraves** [comment]
thanks.  that's fine.

can you also fix the pointer changing to a hand?  i think it should only be a hand if you are over an element you can click on.

**Comment by buob** [comment]
Updated, and added a couple other small fixes

**Comment by buob** [comment]
Added one more commit for opening markdown links in new windows

**Pull request merged**
