### PR TITLE
save table interaction state #3685

### PR DESCRIPTION
**Pull request by mnavasiolava**
save state of the following interactions:
1. filtering/searching
2. data bars, heatmap
3. precision changing
4. column resizing

fixes for saving column types, alignment, visibility

### CODE REVIEW

**Comment by scottdraves** [comment]
kick jenkins

**Comment by scottdraves** [comment]
kick jenkins

**Comment by scottdraves** [comment]
i see the info saved, but when i open a bkr file, it does not seem to apply the state, i get the original.

**Comment by mnavasiolava** [comment]
kick jenkins

**Comment by scottdraves** [comment]
kick jenkins

**Comment by scottdraves** [comment]
:+1:

**Pull request merged**
