### PR TITLE
support 64 bit integers in tables and autotranslation #3332

### PR DESCRIPTION
**Pull request by kpaharelau**
Support for BigInteger has been added.

Use for testing

https://www.dropbox.com/s/3z7wu8300097bau/3332.bkr?dl=0

### CODE REVIEW

**Comment by tomca32** [comment]
kick jenkins

**Comment by scottdraves** [comment]
OK this is a good start but the issue is much larger.  Eventually we are going to need the object format specified in the issue.  But we can get there in some smaller steps.

First step, it should work with Longs in addition to BigIntegers.

Also, add your tutorial as a separate notebook to the tutorials.

**Comment by scottdraves** [comment]
:+1:

**Comment by scottdraves** [comment]
please bring up to date with master.

**Pull request merged**
