### PR TITLE
Handle moving markdown editor up and down

### LINKED ISSUE #350: Markdown cell contents are cleared when they are moved "up" in cell order.
This problem does not happen when you move the cells down however.

### PR DESCRIPTION
**Pull request by samccone**
fixes #350

Due to the way that epic editor works and the way that moving elements
via the cellmanger you need to reinit the markdown editor to reshow the
markdown content.

### CODE REVIEW

**Comment by samccone** [comment]
FYI this PR exacerbates the newline whitespace bug everytime you move up and down

**Comment by scottdraves** [comment]
that sucks :(
what determines when the cell gets a blue outline idk if i've seen that before

**Comment by anglee** [comment]
After this change, an error appears in the console when a markdown cell is inserted:
image

**Comment by anglee** [comment]
I noticed `bkHelper` was injected. bkHelper should never be injected. It should be limited to used by plugins only. core code should use specific services, In this case, `bkSessionManager.isNotebookLocked` should be used.

**Comment by samccone** [comment]
looks like i added this one
https://github.com/twosigma/beaker-notebook/commit/f36f4b57d7e527e7a1ca98e1a3e8103cdcd48c95

just curious as to the difference

**Comment by anglee** [comment]
Just to be clear, using bkHelper has nothing to do with the console error. I just happened to notice both at the same time.

**Pull request merged**
