### PR TITLE
p2 fixes

### PR DESCRIPTION
**Pull request by samccone**

### CODE REVIEW

**Comment by scottdraves** [comment]
please do not show empty parens

**Comment by samccone** [comment]
:+1:

**Comment by anglee** [comment]
I can still reproduce #618 with the `z-index` change

**Comment by anglee** [comment]
Now in advanced mode, the output menu hamburger icon doesn't response to mouse clicks

**Comment by samccone** [comment]
I have dropped that commit for now, so we can get this in

**Pull request merged**
