### PR TITLE
improve file save dialog: handle dirs #3808

### PR DESCRIPTION
**Pull request by kpaharelau**
this is fix for error handling. But dialog doesn't open browsing folder that user selects in input field . I need more time for improvements current functionality.

### CODE REVIEW

**Comment by kpaharelau** [comment]
NOT READY FOR MERGE

**Comment by scottdraves** [comment]
not sure what you mean, will you add the open browsing folder function in the next day or two?

**Comment by scottdraves** [comment]
thanks.  the handling for a directory is good.
but now the dialog starts out with both top-level directories open, that's a problem.

**Comment by scottdraves** [comment]
:+1:

**Pull request merged**
