### PR TITLE
#6647 fix right click on plot in ms edge

### PR DESCRIPTION
**Pull request by MariuszJurowicz**
This bug was caused by the different events dispatch order between MS Edge and other browsers.

### CODE REVIEW

**Comment by scottdraves** [comment]
👍  tested on chrome/mac

**Comment by EfimovVladimir** [comment]
failed on windows/chrome

**Comment by MariuszJurowicz** [comment]
@EfimovVladimir 
Can you be more specific on what's not working?
does it work on edge for you?

**Comment by EfimovVladimir** [comment]
for first right click nothing happens, but for second right click opens menu.
i.e. every second right click opens the menu.
also the double right click opens the menu.

**Comment by EfimovVladimir** [comment]
after rebuilding js for our app the right click started to work fine, so
:+1: tested on chrome/windows

**Pull request merged**
