### PR TITLE
#8246 make beakerx compatible with Jupyterlab 2.0

### PR DESCRIPTION
**Pull request by piorek**

### CODE REVIEW

**Comment by Rep1AI** [comment]
Does beakerx work with Jupyterlab 2.1 or not?

**Comment by karlduderstadt** [comment]
Is this ready for testing? How can we help? Would be wonderful to have beakerx working in Jupyterlab 2.x

**Comment by haobibo** [comment]
any progress on this?

**Comment by ildipo** [comment]
Repository was refactored

**Pull request closed without merging**
