### PR TITLE
#6730: tableDisplay update value

### PR DESCRIPTION
**Pull request by jaroslawmalekcodete**

### CODE REVIEW

**Comment by scottdraves** [comment]
on 2nd thought, i think i just want sendModel to work for the user.  not sure what's wrong this this:
screen shot 2018-02-13 at 1 06 51 pm

**Comment by jaroslawmalekcodete** [comment]
Instead of mapListToUpdate[0]["a"] use tableToUpdate.values[0][0] = 99
like here 
screenshot from 2018-02-14 12-36-19

**Comment by scottdraves** [comment]
OK cool, then we need a way to refer to the data by column name and row instead of just by index.

**Comment by jaroslawmalekcodete** [comment]
updatecellbycolumnname

**Pull request merged**
