### PR TITLE
CodeMirror: gutters selection

### PR DESCRIPTION
**Pull request by alice-kroch**
Issue #3233. Please, check

### CODE REVIEW

**Comment by tomca32** [comment]
Don't forget to remove the gutterClick listener on "destroy" event. Look at the other examples at the bottom of codecell-directive.js

**Comment by tomca32** [comment]
kick jenkins

**Comment by alice-kroch** [comment]
Updated. Please, check.

**Comment by scottdraves** [comment]
If the cell is not focused, and you click a number, then we need to focus on the code mirror.
try this:
1) open a new empty notebook
2) add a code cell and type a line of text
3) click the File menu, then click it again to close it
4) click the "1" to select the line.
5) note the color of the selection is wrong.
6) start typing.  the selection is not replaced.

**Comment by scottdraves** [comment]
also, to make this feature more discoverable, change the mouse to the finger when hovering over the line numbers.

**Comment by alice-kroch** [comment]
Updated.

**Comment by scottdraves** [comment]
if i click and drag from line 1 to line n, then only lines 1 to n-1 are selected.

**Comment by alice-kroch** [comment]
Updated.

**Comment by scottdraves** [comment]
same problem if you drag from line n to line 1, only selects up to line 2.

**Comment by scottdraves** [comment]
:+1:

**Pull request merged**
