### PR TITLE
issue #3312 (SQL login) implemented on new branch

### PR DESCRIPTION
**Pull request by konstantinTarletski**

### CODE REVIEW

**Comment by scottdraves** [comment]
👍 looks good pls bring up to date with master.

**Comment by scottdraves** [comment]
does not log in on the 1st try.  i made a cell that should run in s particular DB, and set up its jdbc string like:

```
jdbc:sqlserver://zzzz.twosigma.com:1433;DatabaseName=xxxxxx;user=yyyyyy;password=<prompt>
```

and then ran the cell, it failed with an error:

```
java.sql.SQLException: Cannot create PoolableConnectionFactory (Login failed for user 'yyyyyyy'. ClientConnectionId:c7c2be9d-5f21-48da-be4b-caa8fe88503c)
```

then i run it and and the 2nd time it prompts for password.  i enter it and the user and get the same error again.

**Comment by scottdraves** [comment]
cool, the login procedure works!  some remaining issues:
1) if you press enter after typing the password, that should be the same as pressing OK
2) if you press ESC or click cancel, then it should fail the execution with an error "no password provided".  right now, if you close the dialog the evaluation gets stuck "pending" and cannot be canceled.

**Comment by scottdraves** [comment]
the connection string should wrap sooner so that a scrollbar does not appear.
"Default data source" should go across the dialog, not be restricted to the left column.
delete "connection string" and start the jdbc string on the left column and let it flow all the way across.

keep only one hrule, the one between the jdbc string and the name field.  delete the other 3 lines.

sql-dialog

**Comment by konstantinTarletski** [comment]
All PR notes are done
Also find out that it was a bug with "h2database", fixed it : write workarond for connection.

**Comment by scottdraves** [comment]
👍 
will merge after the spark changes settle down.

**Pull request merged**
