### PR TITLE
expand outputcontainer options #2997

### PR DESCRIPTION
**Pull request by kpaharelau**
Please test it and send me remarks

### CODE REVIEW

**Comment by tomca32** [comment]
kick jenkins

**Comment by scottdraves** [comment]
kick jenkins

**Comment by scottdraves** [comment]
please bring up to date with master.

**Comment by scottdraves** [comment]
Thank you Cit, we are very close!  But this isn't the right way to get the test to pass.
It needs to have the result that it is checking for.  On this branch in that test notebook, if I evaluate
`beaker.v14` I get a different result (the 3rd part is displayed as ascii not as a table):

screen shot 2015-12-22 at 10 32 01 am

**Comment by kpaharelau** [comment]
I tested on the latest version of this branch
image
image

``` json
  "items": [
    "pippero", 
    [
      1, 
      2, 
      3, 
      4, 
      5, 
      6
    ], 
    {
      "columnNames": [
        "a", 
        "b", 
        "c"
      ], 
      "subtype": "ListOfMaps", 
      "type": "TableDisplay", 
      "types": [
        "integer", 
        "integer", 
        "integer"
      ], 
      "values": [
        [
          1, 
          3, 
          null
        ], 
        [
          4, 
          null, 
          5
        ]
      ]
    }
  ], 
  "labels": [
    "", 
    "", 
    ""
  ], 
  "layout": {
    "borderDisplayed": false, 
    "type": "SimpleLayoutManager"
  }, 
  "type": "OutputContainer"
}
```

This is a version from master
image

``` json

{
  "items": [
    "pippero", 
    [
      1, 
      2, 
      3, 
      4, 
      5, 
      6
    ], 
    {
      "columnNames": [
        "a", 
        "b", 
        "c"
      ], 
      "subtype": "ListOfMaps", 
      "type": "TableDisplay", 
      "types": [
        "integer", 
        "integer", 
        "integer"
      ], 
      "values": [
        [
          1, 
          3, 
          null
        ], 
        [
          4, 
          null, 
          5
        ]
      ]
    }
  ], 
  "type": "OutputContainer"
}
```

Please retest

**Comment by scottdraves** [comment]
this should clarify:
screen shot 2015-12-23 at 10 14 28 am

**Comment by scottdraves** [comment]
:+1:

**Pull request merged**
