### PR TITLE
Init indicator improvements (new branch)

### PR DESCRIPTION
**Pull request by alice-kroch**
Issue #3001. Please, check

### CODE REVIEW

**Comment by scottdraves** [comment]
please do not move the menu to the left.

**Comment by scottdraves** [comment]
it should look like this:
screen shot 2015-12-03 at 222

**Comment by alice-kroch** [comment]
Probably it's not a good idea. If i leave menu margin 20px it's buttons will overlap power button
overlap
overlap2

So I adjusted menu margin value only for advanced mode.

**Comment by scottdraves** [comment]
indeed but this is a smaller problem, please just do it.

**Comment by scottdraves** [comment]
:+1:

**Pull request merged**
