### PR TITLE
Fix epiceditor resizing on editing

### PR DESCRIPTION
**Pull request by samccone**

### CODE REVIEW

**Comment by scottdraves** [comment]
:dolphin:

**Comment by samccone** [comment]
:ocean: :ocean: :ocean: :octopus: :ocean:

**Comment by anglee** [comment]
@samccone nice! I am curious how you found this?

**Comment by samccone** [comment]
I pretty much just scraped all the issues and all of the prs and all the commits of epic editor and found this gem https://github.com/Gankro/EpicEditor/commit/916e9c15d5e74de60053f287bd9e71b256de16f5#commitcomment-7771558

**Pull request merged**
