### PR TITLE
#2475  Clojure autotranslation

### PR DESCRIPTION
**Pull request by maksim-lauryk**
#2475  Clojure autotranslation

### CODE REVIEW

**Comment by ildipo** [comment]
Hi Max, a couple of changes:
1) move the code template for get and set into a file so it is easier to change it
2) rather than using the proxy you wrote for converting type you should use the serialization and deserialization hooks: look in `plugin/scala/src/main/scala/com/twosigma/beaker/scala/util/ScalaEvaluator.java` at line 122 to 137 and to the classes it uses, it shows how you can extend the auto translation for new language-specific types. This way you'll be able to pass directly a clojure object into the NamespaceClient functions.

**Comment by maksim-lauryk** [comment]
the code template for an internal Clojure initializing was moved to external file;
added the deserialization hooks;

**Comment by ildipo** [comment]
:+1:

**Comment by scottdraves** [comment]
:+1: 
please resolve merge conflicts.

**Comment by maksim-lauryk** [comment]
the conflicts were resolved, code is up to date with master

**Pull request merged**
