### PR TITLE
#2679. click filename to change

### PR DESCRIPTION
**Pull request by maxyeg**

### CODE REVIEW

**Comment by scottdraves** [comment]
cool.  but:
1) if the file has not been saved yet, this will crash.  in that case, clicking on "New Notebook" should just be like an orderinary save.
2) if the file has been saved, the button at the bottom of the dialog should read "Rename" instead of "Save"

**Comment by scottdraves** [comment]
if the document is unsaved and i rename it, then the \* in the title of the window should not vanish.

**Comment by tomca32** [comment]
On the frontend we have a couple of modules/files that are essentially dumping grounds for everything, such as mainapp.js that is edited here.

I feel like we have an opportunity here to make the codebase a bit healthier by separating this "I/O" stuff into its own service - fileManipulation.js or something. I think it would make sense to have loading/saving/renaming logic in there rather than in a file called "mainapp.js".

If it's not a big refactor and I don't feel it is, maybe we could consider it.

**Comment by scottdraves** [comment]
sure that's fine.

**Comment by scottdraves** [comment]
:+1:

**Pull request merged**
