### PR TITLE
Lazily delete attachments when publishing notebooks

### PR DESCRIPTION
**Pull request by grin**
Fixes: https://github.com/twosigma/beaker-notebook/issues/2451

### CODE REVIEW

**Comment by scottdraves** [comment]
the 1st publication ended up with a broken image like this one:
https://pub.beakernotebook.com/#/publications/5609dbcb-27ef-4dd2-a459-17946a59d936

**Comment by grin** [comment]
I tested image upload with code in this PR and the publication api url in Beaker set to `https://pub-staging.beakernotebook.com`...and it worked for me, see the publication titled `3` by bartek. What was your setup when you were testing this?

**Comment by grin** [comment]
Also, this should only work on https://pub-staging.beakernotebook.com/#/publications because image scaling was only deployed there.

**Comment by ildipo** [comment]
That's correct - I'll re-deploy as soon as beaker build works

**Pull request merged**
