### PR TITLE
Fix for scala spark - make sure you use the one compiled for scala 2.11

### PR DESCRIPTION
**Pull request by ildipo**
Fix issue #1867 - you MUST also use spark built for scala 2.11

### CODE REVIEW

**Comment by syepes** [comment]
Is there anyway we could also make this work with Scala 2.10, as 2.11 is not used everywhere

**Comment by scottdraves** [comment]
beaker comes only with scala 2.11 so this restriction does not seem out of order.
i would love it if we could improve it but i don't know how and we are out of time for v1.4 release.

**Comment by ildipo** [comment]
We can compile the plugin with 2.10 - even distribute two plugins (one 2.11 and one 2.10 scala)

**Comment by ildipo** [comment]
It looks like 2.11 has some breaking changes since all previous versions work with the same spark

**Comment by scottdraves** [comment]
i am OK with moving plugin back to 2.10, Sebastian you probably know more about scala users than I do, what do you think?

**Comment by scottdraves** [comment]
please move discussion to Issue #2499

**Pull request merged**
