### PR TITLE
Mf/namespace css task

### PR DESCRIPTION
**Pull request by mforsyth**
Hi @ildipo ... this limits the "namespacing of CSS" behavior that I have mentioned to only the embedded build (which is the only place where it will be relevant).

It also publishes certain static assets which are meant to be used externally (the js and css assets needed for embeddable beaker).

### CODE REVIEW

**Comment by ildipo** [comment]
The output stuff should go in a different directory (e.g. output) and it should not be added to the repo

**Comment by ildipo** [comment]
I tried gradle check and it works - seems to fail on travis....

**Comment by ildipo** [comment]
Actually technically speaking data is NOT build - it is used to build. You can re-generate its content through a gradle target but its purpose is to provide input to build stuff.

**Comment by mforsyth** [comment]
@ildipo ready

**Pull request merged**
