### PR TITLE
Menu in beaker object interface

### PR DESCRIPTION
**Pull request by alice-kroch**
Issue #3532. Please, check.

### CODE REVIEW

**Comment by scottdraves** [comment]
1) the triangle for the menu should point down, not right.
2) the display should update after you make a change.
3) i tried delete, and it deleted all the properties, not just the one i selected.
4) i tried rename, and it renamed correctly, but it deleted all the other properties.

**Comment by scottdraves** [comment]
1 and 2 seem fixed, thanks
but 3 and 4 are still a problem...

**Comment by scottdraves** [comment]
3+4 seem fine now.

still needs to focus on text field when the rename dialog opens, and fix color of the menu in default theme (should be green matching the language menu in cells in nonadvanced mode).

**Comment by kpaharelau** [comment]
spot [5:21 PM] 
ah

[5:21] 
these changes for the beaker object should not apply the the output container

[5:21] 
i did not intend for output containers to have menus

[5:21] 
only the beaker object

[5:21] 
i guess it should be another kind of container

**Comment by scottdraves** [comment]
great.  a few remaining details:
1) remove the "beaker object menu" tooltip
2) bring up to date with master
3) the triangle is wrong. it is narrower than the one in the language menu:
screen shot 2016-03-21 at 11 32 25 am
screen shot 2016-03-21 at 11 32 13 am
4) the text does not highlight and the cursor does not change to the finger in a large enough area.  if you point between the triangle and the text, or below the triangle, then it does not activate.  it should be active in the whole area around.
untitled 2

**Pull request merged**
