### PR TITLE
vim mode cmd box partially obscured by line numbers #4283

### PR DESCRIPTION
**Pull request by mnavasiolava**
i included CodeMirror's css used in vim mode. so now search box looks like:

image

### CODE REVIEW

**Comment by scottdraves** [comment]
looks good in regular mode but comes out wrong in advanced mode.
screen shot 2016-06-20 at 10 21 46 am

**Comment by mnavasiolava** [comment]
fixed

**Comment by scottdraves** [comment]
the editor mode should not change the layout of the cells.
it looks like this is introducing a vertical margin for the vim cmd box.
that is not needed, the box can sit over the other UI.  it just should not be under anything.

**Comment by scottdraves** [comment]
please position the cmd box below the last line of code.

**Pull request merged**
