### PR TITLE
delete all output cell should NOT delete the one under execution #1343

### PR DESCRIPTION
**Pull request by mnavasiolava**

### CODE REVIEW

**Comment by scottdraves** [comment]
this doesn't work for me.  try this:
open the JavaScript tutorial.
run the 2nd cell (start the game).
Delete all output cells.
see that you cannot cancel anymore.

**Comment by mnavasiolava** [comment]
fixed. also removed deleted cells from evaluation queue as Davide asked

**Comment by scottdraves** [comment]
it looks like it will not remove it from the evaluation queue if it has no output, i think this is a mistake.

**Comment by mnavasiolava** [comment]
but "delete all output cell" concerns only cells with output.
and btw, if the cell is in the evaluation queue, it will always have output "pending" or "running" and that's why will be deleted. am i wrong?

**Comment by scottdraves** [comment]
:+1: you are right, thanks.

**Pull request merged**
