### PR TITLE
#5488 set CodeMirror font to Roboto Mono

### PR DESCRIPTION
**Pull request by jszalek**

### CODE REVIEW

**Comment by scottdraves** [comment]
```
986a6b806b2af9a5fae0d8c22efa9bba.woff Failed to load resource: the server responded with a status of 404 (Not Found)
8457d45af7977d957c043bf0afa59818.ttf Failed to load resource: the server responded with a status of 404 (Not Found)
```
and code appears in default font.

**Comment by scottdraves** [comment]
server log says:
```
[W 11:29:33.280 NotebookApp] 404 GET /notebooks/demoFiles/986a6b806b2af9a5fae0d8c22efa9bba.woff (::1): No such file or directory: demoFiles/986a6b806b2af9a5fae0d8c22efa9bba.woff
```
it's trying to load it relative to the noteobok, not from our extension, where it exists:
```
$ find . -name 986a6b806b2af9a5fae0d8c22efa9bba.woff
./beakerx/beakerx/static/986a6b806b2af9a5fae0d8c22efa9bba.woff
```

**Comment by jszalek** [comment]
@scottdraves I cannot reproduce. Could you provide me more information?

**Comment by scottdraves** [comment]
here's the DOM element being inserted:
```
@font-face{font-family:Roboto Mono;src:url(cc410562b337814660674104e9561a51.eot);src:url(cc410562b337814660674104e9561a51.eot?#iefix) format("embedded-opentype"),url(986a6b806b2af9a5fae0d8c22efa9bba.woff) format("woff"),url(8457d45af7977d957c043bf0afa59818.ttf) format("truetype"),url("e9529347be225cb9eac9ee6790409bdc.svg#Roboto Mono") format("svg");font-style:normal;font-weight:400}.CodeMirror pre{font-family:Roboto Mono}
```
there is no path to the font assets given.  if i manually edit that to:
```
@font-face{font-family:Roboto Mono;src:url(cc410562b337814660674104e9561a51.eot);src:url(cc410562b337814660674104e9561a51.eot?#iefix) format("embedded-opentype"),url(../nbextensions/beakerx/986a6b806b2af9a5fae0d8c22efa9bba.woff) format("woff"),url(8457d45af7977d957c043bf0afa59818.ttf) format("truetype"),url("e9529347be225cb9eac9ee6790409bdc.svg#Roboto Mono") format("svg");font-style:normal;font-weight:400}.CodeMirror pre{font-family:Roboto Mono}
```
then boom the roboto appears.

**Comment by scottdraves** [comment]
also, do we really need svg and eot formats?

**Comment by scottdraves** [comment]
another thing to check: what if the user sets this CSS in their custom.css?
their personal preference should override our extension.

**Comment by LeeTZ** [comment]
@jszalek  I check it out on my laptop and get same 404 errors in console and server log.

**Comment by jszalek** [comment]
eot is for IE9, svg for legacy iOS devices - I think we can remove it

**Comment by scottdraves** [comment]
xlnt that fixes the problem.  now we have to allow custom.css to override it.

**Comment by scottdraves** [comment]
You can detect if a custom font has been loaded with something like:
```
var elem = document.getElementsByClassName('CodeMirror-line')[0]
var font_is_default = window.getComputedStyle(elem).getPropertyValue('font-family') === 'monospace'
```
unclear if this depends on the browser version/platform?

**Comment by jszalek** [comment]
this method can return different values depends on browser but in our case (font-family) it is the same on every engine

**Pull request merged**
