### PR TITLE
Katex Cleanups

### PR DESCRIPTION
**Pull request by buob**

### CODE REVIEW

**Comment by buob** [comment]
This doesn't include embeddable_assets, launcher, or [iPython3 outputarea](https://github.com/twosigma/beaker-notebook/blob/master/plugin/ipythonPlugins/src/dist/vendor/ipython3/outputarea.js#L590-L602)

**Comment by scottdraves** [comment]
embeddable_assets and launcher we'll deal with separately.

should include IPython v3 though. however, looks like IPy v2 is not working:

screen shot 2015-04-29 at 5 52 24 pm

**Comment by ildipo** [comment]
Scott, are you sure this worked before? I think we have a github issue for 'support Latex output from python'

**Comment by scottdraves** [comment]
you are right https://github.com/twosigma/beaker-notebook/issues/85

**Pull request merged**
