### PR TITLE
do not show day of week in timeseries axis labels #3023

### PR DESCRIPTION
**Pull request by kpaharelau**
Date format "YYYY MMM DD ddd, HH:mm" has been changed to the "YYYY MMM DD, HH:mm"
Date format "YYYY MMM DD ddd" has been changed to the "YYYY MMM DD"

### CODE REVIEW

**Comment by scottdraves** [comment]
i not not seeing day numbers at all now.  
screen shot 2015-12-07 at 12 54 12 pm

**Comment by scottdraves** [comment]
note that i actually think that not showing the days at all is best for this graph, if you do that then the lines have to be on the 1st of the month.  these lines are on various days of the month as the interval is like 45 days.

since fixing that is more complex, right now please just remove the day-of-week string.

**Comment by kpaharelau** [comment]
> > since fixing that is more complex, right now please just remove the day-of-week string. 

 it was a  solution for  this issue. 

According "i not not seeing day numbers at all now.". We a re using time format "YYYY MMM" for time spans less then year but greater then month.

**Comment by scottdraves** [comment]
:+1:

**Pull request merged**
