### PR TITLE
#6640 python table formatting for dates not working

### PR DESCRIPTION
**Pull request by rbidas**

### CODE REVIEW

**Comment by scottdraves** [comment]
looks good pls bring up to date with master

**Comment by rbidas** [comment]
Done

**Comment by scottdraves** [comment]
now it breaks the previous fix, running the cell
```
TableDisplay([{'y1':4, 'm3':2, 'z2':1}, {'m3':4, 'z2':2}])
```
see https://github.com/twosigma/beakerx/issues/6638

**Comment by rbidas** [comment]
done

**Pull request merged**
