### PR TITLE
When loading a notebook by http from same host, don't proxy.

### PR DESCRIPTION
**Pull request by mforsyth**
NOTE: Travis currently failing, but with same errors as master.

### CODE REVIEW

**Comment by scottdraves** [comment]
hi what's the motivation for this PR?

**Comment by mforsyth** [comment]
In an external system, when a user opens a notebook, it loads the notebook contents from a url that is from the same host & port as the main document containing the Beaker interface.  For this reason, there's no need to proxy the request through the Beaker server, since CORS will never block the AJax request (it's for the same host and port as the main window).

Also, if we DID try to proxy the request, it wouldn't work, because the Beaker server (being a container running inside external network) won't be able to load the notebook contents - it woudn't have the right cookies to gain access, and actually DNS resolution would be different from inside the container & the request wouldn't go to the right place.

**Comment by scottdraves** [comment]
shouldn't external system have its own location type instead of using location_http?
what happens when you try to save?

**Comment by mforsyth** [comment]
@scottdraves I'd be open to making a separate location type.  I just figured it actually still was using http, so it would fall under http....  

We've always been using a separate save function to save notebook contents... I haven't actually gotten to the point of calling a builtin Beaker function to do the saving yet.

Does this existing http location type support saving back to the original url of the file?  Via a POST?

**Comment by scottdraves** [comment]
it just crashes if you try that :) https://github.com/twosigma/beaker-notebook/issues/1523
thanks for prompting me to test it.

yes please make a location type, this is exactly what they are for.

**Comment by mforsyth** [comment]
Sounds good @scottdraves

**Pull request closed without merging**
