### PR TITLE
Enhanced plot styling

### PR DESCRIPTION
**Pull request by ssadedin**
This change lets the user style plot elements directly using CSS.

Note: this is an updated version of https://github.com/twosigma/beaker-notebook/pull/4895 and supercedes it.

There are two levels of styling this allows - the "normal" level and "advanced".

## Normal Level Styling

The normal level offers three new plot properties for setting styles:

 * labelStyle (and also labelXStyle and labelYStyle)
 * titleStyle
 * gridLineStyle

These can be set to any CSS styles applicable to the relevant plot elements. For example, `font-style: bold` or `font-size: 32px`, etc.

Example code:

```groovy
r = new Random()
new Plot(title: "Random Gaussian Points",
         labelStyle: "font-size:32px; font-weight: bold; font-family: courier; fill: green;",
         gridLineStyle:  "stroke: purple; stroke-width: 3;",
         titleStyle: "color: green;"
        ) \
  << new Points(
                x: (1..1000).collect { r.nextGaussian() * 10.0d },
                y: (1..1000).collect { r.nextGaussian() * 20.0d }
               )
```

**Result**:

image

## Advanced level styling

This level injects complete CSS style blocks into the code with minimal support to scope the styles to the plot at hand. Using this feature is not recommended because the styles can escape and affect other elements of the page or other plots if not used carefully. However I left this in as it does allow a level of flexibility that can help in situations where no other solution will do.

Example code:

```groovy
r = new Random()
new Plot(title: "Random Gaussian Points",
         customStyles: [
           ".plot-label { font-size:32px; font-weight: bold; font-family: courier; fill: green;}",
           ".plot-gridline { stroke: purple; stroke-width: 3; }",
         ]
        ) \
  << new Points(
                x: (1..1000).collect { r.nextGaussian() * 10.0d },
                y: (1..1000).collect { r.nextGaussian() * 20.0d }
               )
```

Result:

image

### CODE REVIEW

**Comment by scottdraves** [comment]
thanks that looks great will try it out tomorrow

**Comment by scottdraves** [comment]
Thanks, it runs great except if i right-click and save-as png or svg.  then i just get a JS console error:
beakerOutputDisplay.js:16175 Uncaught ReferenceError: customStyles is not defined(…)

**Comment by ssadedin** [comment]
Will look into that - I tested it at some point but something must have
gotten broken in my last tweaks to it. Thanks!

**Comment by ssadedin** [comment]
Latest push should fix the javascript error on saving to SVG.

**Comment by scottdraves** [comment]
thanks!

**Pull request merged**
