### PR TITLE
mac electron build can fail #3634

### PR DESCRIPTION
**Pull request by kpaharelau**
I have added removing osxdmg directory.  Ant moving task worked incorrectly with this directory.

### CODE REVIEW

**Comment by kpaharelau** [comment]
kick jenkins

**Comment by kpaharelau** [comment]
kick jenkins

**Comment by kpaharelau** [comment]
kick jenkins

**Comment by kpaharelau** [comment]
kick jenkins

**Comment by scottdraves** [comment]
i still get this error if i make it twice in a row:

```
Done running the applescript...
Fixing permissions...
Done fixing permissions.
Blessing started
Blessing finished
Unmounting disk image...
"disk2" unmounted.
"disk2" ejected.
Compressing disk image...
Preparing imaging engine…
Reading Protective Master Boot Record (MBR : 0)…

hdiutil: convert failed - File exists
:makeInstaller FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':makeInstaller'.
> Process 'command './create-dmg/create-dmg'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Pull request merged**
