### PR TITLE
Fix #618, do not handle click in output area

### LINKED ISSUE #618: cannot select text in cell output that's an error
the first line you can highlight but it does not stay selected so that i can copy it.
the expanded msg cannot be highlighted at all.

### PR DESCRIPTION
**Pull request by anglee**

### CODE REVIEW

**Comment by samccone** [comment]
:+1:

**Comment by scottdraves** [comment]
this breaks clicking on cell backgrounds.
we need to fix that fix, not undo it!

**Comment by anglee** [comment]
done

**Comment by scottdraves** [comment]
thanks

**Pull request merged**
