### PR TITLE
Issue #4095 - default sorting for tables - server ordering fix

### PR DESCRIPTION
**Pull request by dmtrius**
default sorting for tables - server ordering fix

### CODE REVIEW

**Comment by dmtrius** [comment]
kick jenkins

**Comment by EfimovVladimir** [comment]
For this PR. In Beaker you can open file   ..\beaker-notebook\test\notebooks\tables-test.bkr. Then run second cell (title "Table with Index column"). Which the first row will be in table?  Test on Jenkins have gotten 1st row with index 4.

**Comment by scottdraves** [comment]
test "should be sorted by server" seems to be failing not sure why jenkins did not flag it.

**Comment by scottdraves** [comment]
please bring up to date with master and fix tests.

**Comment by dmtrius** [comment]
kick jenkins

**Comment by dmtrius** [comment]
kick jenkins

**Pull request merged**
