### PR TITLE
Update plugin manager style

### LINKED ISSUE #495: Update plugin manager styling per new UI

### PR DESCRIPTION
**Pull request by samccone**
fixes #495

### CODE REVIEW

**Comment by scottdraves** [comment]
missing the button around "from url..."

**Comment by scottdraves** [comment]
when the buttons are clicked you get a blue outline that is partially obscured.  please remove it.

**Comment by scottdraves** [comment]
buttons should not be clickable if they are already loaded or loading.

**Comment by samccone** [comment]
ok i updated the style issues, per 

> buttons should not be clickable if they are already loaded or loading.

Want to open a new issue and I can resolve that since that is new functionality?

**Comment by scottdraves** [comment]
thanks.  OK yes I will handle the reclick issue through another issue assigned to me.

For the "From URL" button, the bullet should be invisible but the same size as the other buttons.
That will should the 1-pixel gap above it.

screen shot 2014-08-25 at 1 19 32 pm

**Comment by samccone** [comment]
ah good spot, was unsure about how we wanted it to really look. updating now

**Comment by samccone** [comment]
all updated @scottdraves

**Pull request merged**
