### PR TITLE
marina/nanoplot

### PR DESCRIPTION
**Pull request by mnavasiolava**
Nanoplot example was added to Interactive Charts tutorial

### CODE REVIEW

**Comment by scottdraves** [comment]
```
def ch = new Crosshair(color: new Color(255, 128, 5), width: 2, style: StrokeType.DOT)
def pp = new NanoPlot(useToolTip: true, showLegend: true, crosshair: ch, omitCheckboxes: true,
                  legendLayout: LegendLayout.HORIZONTAL, legendPosition: LegendPosition.TOP)
pp << new Line(displayName: "Line", x: [1, 4, 6, 8, 10], y: [3, 6, 4, 5, 9], width: 3)
pp << new Bars(displayName: "Bar", x: (1..10), y: [1, 2, 3, 4, 3, 2, 1, 2, 3, 4],
               color: new Color(0, 0, 128, 160), outlineColor: Color.black, width: 0.5)
pp << new Points(displayName: "", x: [1, 4, 6, 8, 10], y: [3, 6, 4, 5, 9],
                 color: new Color(128, 0, 0, 160), outlineColor: Color.black, size: 10) // not show in the legend box
```

this example from the plotting tutorial i changed to a nanoplot, and then the graphics are mangled and there's a warning about unordered data.

**Comment by scottdraves** [comment]
:+1: :+1:

**Comment by scottdraves** [comment]
merge please

**Comment by mnavasiolava** [comment]
done

**Pull request merged**
