### PR TITLE
4740 add hysteresis to submenu closing

### PR DESCRIPTION
**Pull request by sluhtoja**

### CODE REVIEW

**Comment by scottdraves** [comment]
test failure is real, it's not hard to get multiple open menus
screen shot 2016-09-22 at 10 54 47 am

also i don't want to merge this until https://github.com/twosigma/beaker-notebook/issues/4739 is fixed.

**Comment by scottdraves** [comment]
still broken in weird ways.  for example:
opening and mouseover the cell output menu resulted in:
screen shot 2016-09-23 at 1 31 56 pm
and jenkins also failing.

**Comment by sluhtoja** [comment]
kick jenkins

**Comment by scottdraves** [comment]
behavior looks good but still failing jenkins and does not look like a flake:

```
Cell Menu
[firefox #1-7]     ✓ closes when another menu is opened
[firefox #1-7]     ✗ closes by clicking outside
```

**Comment by scottdraves** [comment]
great thanks for fixing the tests.  but when i hover over the File>Save As menu item, I get a weird extra item appearing:

screen shot 2016-09-27 at 10 51 28 am

**Pull request merged**
