### PR TITLE
#2068 if flash is missing (replace ZeroClipboard mechanism)

### PR DESCRIPTION
**Pull request by dlukyanyuk**
_ZeroClipboard swf_ mechanism was replaced to _document.execCommand_ technique.

### CODE REVIEW

**Comment by dlukyanyuk** [comment]
Should I totally remove ZeroClipboard?

**Comment by scottdraves** [comment]
if the new api is missing or disabled (in firefox it is config option) then
use flash.

BeakerNotebook.com
ScottDraves.com
twitter.com/Scott_Draves

**Comment by scottdraves** [comment]
Document scrolls to bottom on copy, this is a bug.

**Comment by scottdraves** [comment]
eg, broken on firefox for me:

```
Exception { message: "", result: 2147500037, name: "NS_ERROR_FAILURE", filename: "http://127.0.0.1:8801/c09090b/beaker/app/dist/beakerOutputDisplay.js", lineNumber: 281, columnNumber: 0, inner: null, data: null, stack: ".controller/$scope.doCopyToClipboard/executeCopy@http://127.0.0.1:8801/c09090b/beaker/app/dist/beakerOutputDisplay.js:281:14
.controller/$scope.doCopyToClipboard@http://127.0.0.1:8801/c09090b/beaker/app/dist/beakerOutputDisplay.js:285:12
Parser.prototype.functionCall/<@http://127.0.0.1:8801/c09090b/beaker/app/dist/beakerVendor.js:45525:14
@http://127.0.0.1:8801/c09090b/beaker/app/dist/beakerVendor.js:59843:8
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://127.0.0.1:8801/c09090b/beaker/app/dist/beakerVendor.js:47433:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://127.0.0.1:8801/c09090b/beaker/app/dist/beakerVendor.js:47531:17
@http://127.0.0.1:8801/c09090b/beaker/app/dist/beakerVendor.js:59842:6
jQuery.event.dispatch@http://127.0.0.1:8801/c09090b/beaker/app/dist/beakerVendor.js:10682:14
$event.dispatch@http://127.0.0.1:8801/c09090b/beaker/app/dist/beakerVendor.js:89497:8
jQuery.event.add/elemData.handle@http://127.0.0.1:8801/c09090b/beaker/app/dist/beakerVendor.js:10367:5
" }
```

**Comment by scottdraves** [comment]
:+1:

**Pull request merged**
