### PR TITLE
#6238 Fixed interactive demo.

### PR DESCRIPTION
**Pull request by michalgce**
I decided to disable continuous_update for slider to provide user better experience during changing value

### CODE REVIEW

**Comment by scottdraves** [comment]
cool works better.
i think setContinuous_update false is a problem, but need to see the parametric graph first.

**Comment by michalgce** [comment]
Take a look on last cell in notebook

**Comment by michalgce** [comment]
I've added new plot.

**Comment by scottdraves** [comment]
ok the main thing this needs is interact() should run once when it's first creates the widgets.
in the last cell when i run it i get the widgets but the result is just "null" until i move the sliders the first time.  the plot appear from the get-go.

**Comment by scottdraves** [comment]
and in the last example the sliders should be doubles.

**Comment by scottdraves** [comment]
i tried making the sliders update continuously again and it didn't work.
i think that's needed.

**Comment by scottdraves** [comment]
and actually, delete all the examples except the last.

**Comment by michalgce** [comment]
[] first creates the widgets

**Comment by scottdraves** [comment]
great it starts out rendered, thanks.

still needs
1) continuous update
2) floating point
3) delete all examples but last

**Pull request merged**
