### PR TITLE
'SVGElement.offsetHeight' is deprecated #3621

### PR DESCRIPTION
**Pull request by kpaharelau**
I will try to use
var W = scope.jqsvg.get(0).clientWidth, H = scope.jqsvg.get(0).clientHeight;
instead
var W = scope.jqsvg.width(), H = scope.jqsvg.height();

All works fine.

I think that this is solution for all jquery elements contains SVGElements. It will be fixed in the 3.0.0 jquery version. But 3.0.0-beta1 doesn't work correctly with our application.

### CODE REVIEW

**Comment by kpaharelau** [comment]
kick jenkins

**Comment by kpaharelau** [comment]
kick jenkins

**Comment by scottdraves** [comment]
:+1:

**Comment by kpaharelau** [comment]
kick jenkins

**Comment by kpaharelau** [comment]
kick jenkins

**Comment by kpaharelau** [comment]
kick jenkins

**Comment by kpaharelau** [comment]
kick jenkins

**Pull request merged**
