### PR TITLE
fix File open dialog sort should persist #2305

### PR DESCRIPTION
**Pull request by kpaharelau**
sort options saved as preferences

### CODE REVIEW

**Comment by ildipo** [comment]
Hi,
It works but I'm getting this exception when I change the sort by:

java.nio.file.NoSuchFileException: /Users/davidepasetto/.beaker/v1/config/beaker.pref.json.tmp
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
    at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:409)
    at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
    at java.nio.file.Files.move(Files.java:1395)
....

**Comment by scottdraves** [comment]
For me, it corrupted the prefs file to end like this:

```
  "advanced-mode" : true,
  "fs-reverse" : true
} true
}
```

**Comment by scottdraves** [comment]
why is this changing the mechanism to write the prefs file?
it should just add another name/value pair.

**Comment by scottdraves** [comment]
we should look at this later, after 1.4 is done

**Pull request closed without merging**
