### PR TITLE
PR for issue 4508 "notifications for run-all progrress"

### PR DESCRIPTION
**Pull request by konstantinTarletski**

### CODE REVIEW

**Comment by scottdraves** [comment]
cool.  but if there is an error, and evaluation stops, the notification should still go out (and report the error).

**Comment by scottdraves** [comment]
also, i set

```
beakerRegister.evaluationFinishedNotificationUrl = "/mailme"
```

but did not see the corresponding menu item.

**Comment by konstantinTarletski** [comment]
I move code written by Sergei from 
outputdisplay-directive.js

to the

 /core/src/main/web/app/helpers/core.js
 function initAvailableNotificationMethods()
line 1780

so if it works , then for both porgres bars
if not , then either for both

So menu should be similar.

**Comment by scottdraves** [comment]
I see different menus when I actually run it:
screen shot 2016-07-25 at 11 42 52 am
screen shot 2016-07-25 at 11 43 24 am

**Pull request merged**
