### PR TITLE
Update notebook version requirements

### PR DESCRIPTION
**Pull request by haobibo**
notebook 5.7.6 fixed a kernel bug.
Please refer to: https://github.com/jupyter/notebook/issues/4439

### CODE REVIEW

**Comment by haobibo** [comment]
@LeeTZ - Please review and consider include this in the next release!

**Comment by LeeTZ** [comment]
Thanks for the PR. We use yaml to install now (configuration.yml). If you could update that I am happy to merge this PR

**Comment by haobibo** [comment]
rebase, reopen

**Comment by haobibo** [comment]
@LeeTZ Done.
Rebased to the new version and updated the onfiguration.yml

**Pull request merged**
