### PR TITLE
A basic node.js plugin that executes javascript code in a remote node ap...

### PR DESCRIPTION
**Pull request by planetmcd**
...plication.

### CODE REVIEW

**Comment by scottdraves** [comment]
this is a big improvement.  two remaining problems:
- still need the installApp target to run "npm install".  need to add your subdir to settings.gradle
- undefined produces an error.  try `var x=1;`

**Comment by planetmcd** [comment]
On the first point, I added the npm install command to the shell script, with the thinking that it would remove an additional dependency on Java.  I can move it to gradle if that makes more sense.

**Comment by scottdraves** [comment]
yea def move to gradle this is a build-time event.

**Comment by scottdraves** [comment]
and when an error is reported, the background of the result cell should be red.
the innertype of the modelOutput.result should be set to "Error".

**Comment by jchendy** [comment]
I'm excited to see how this turns out! FYI, I just published our user-facing expectations for new plugins on the wiki: https://github.com/twosigma/beaker-notebook/wiki/Eval-plugin-spec

**Comment by scottdraves** [comment]
i just made these fixes myself on master.
i also just noticed syntax highlighting is not working, will get that too.

**Comment by planetmcd** [comment]
Sorry I saw the note on the gradle changes, made the changes, and pushed before I saw your second note.

**Pull request merged**
