### PR TITLE
#4338 keybindings to raise and lower section heading level, notebook dirty when changed, added 

### PR DESCRIPTION
**Pull request by sluhtoja**
#4376 raise/lower section should mark notebook as dirty
#4338 cmd-alt 1-4 to insert-after

### CODE REVIEW

**Comment by scottdraves** [comment]
looks like you reformatted the javascript.  please do not change the formatting of the code except the part you need for your work.  also, the formatting you used is incorrect anyway.  we use 2-space indentation and generally follow the google style guide for JS: https://github.com/twosigma/beaker-notebook/wiki/Style-Guide

**Comment by sluhtoja** [comment]
Did not notice, my hands to it automatically.

**Comment by scottdraves** [comment]
no problem -- just fix and push.  the functionality seems fine but i can't check the code without being able to see a diff.  also i recommend you review diffs yourself when you make a PR to be sure your changes are exactly as you want, with no test code left in.

**Comment by sluhtoja** [comment]
will do

**Comment by sluhtoja** [comment]
pushed, I set my indentation to 2.

**Pull request closed without merging**
