### PR TITLE
add table main menu command #3778. Reset all

### PR DESCRIPTION
**Pull request by mnavasiolava**

### CODE REVIEW

**Comment by mnavasiolava** [comment]
kick jenkins

**Comment by scottdraves** [comment]
does not reset sort column.

click on a column to sort by it, then reset, and it remains sorted.
i am testing with the R examples notebook.

**Comment by mnavasiolava** [comment]
sort reset was fixed. also sorting info is saved to state now

**Comment by scottdraves** [comment]
still not working for me.
on the r-examples i click a column to sort, then reset has no visible effect and no error.

**Comment by scottdraves** [comment]
:+1:

**Comment by scottdraves** [comment]
kick jenkins

**Comment by scottdraves** [comment]
looks like you merged when i had a bad commit in master...
please merge again.  sorry my fault.

**Comment by scottdraves** [comment]
bring up to date please

**Comment by mnavasiolava** [comment]
done

**Pull request merged**
