### PR TITLE
CategoryLines style ignored #3387

### PR DESCRIPTION
**Pull request by kpaharelau**
Processing for the 'styles' property has been added.

use https://www.dropbox.com/s/zwvkg2ctfnd9fyj/3387.bkr?dl=0
for testing

### CODE REVIEW

**Comment by scottdraves** [comment]
please add to CategoryLines example in tutorial.

**Comment by scottdraves** [comment]
kick jenkins.

**Comment by kpaharelau** [comment]
kick jenkins.

**Comment by scottdraves** [comment]
:+1:

**Pull request merged**
