### PR TITLE
PR for issue #4482 "add download as CSV item"

### PR DESCRIPTION
**Pull request by konstantinTarletski**

### CODE REVIEW

**Comment by scottdraves** [comment]
kick jenkins

**Comment by scottdraves** [comment]
CSV files I get from this have no rows, just the headers.

**Comment by konstantinTarletski** [comment]
Strange. I used same method as export. Will check tomorrow.

3 Авг 2016 г. 19:28 пользователь "Scott Draves" notifications@github.com
написал:

**Comment by scottdraves** [comment]
👍 function is good, but the test failure is legit.
since this is an emergency, just disable the test (test/tests/tables.js).
also a UI detail: remove the hrule between "Save selected as CSV" and "Download all as CSV".

**Pull request merged**
