### PR TITLE
4780 move column section to top of table menu

### PR DESCRIPTION
**Pull request by sluhtoja**

### CODE REVIEW

**Comment by scottdraves** [comment]
there is a stray hrule.  it should not be the 1st item, it should divide the items into the same groups as before.
screen shot 2016-10-18 at 9 48 05 am

**Comment by scottdraves** [comment]
kick jenkins

**Comment by scottdraves** [comment]
the tests need to be updated for the new menu, this is not a flake.

**Comment by sluhtoja** [comment]
kick jenkins

**Comment by scottdraves** [comment]
tests still failing

```
Table Menu
[firefox #1-23]       ✗ should contain items
[firefox #1-23]         - Expected 'Deselect All Rows' to be 'Deselect All'.
```

**Comment by scottdraves** [comment]
kick jenkins

**Comment by scottdraves** [comment]
kick jenkins

**Pull request merged**
