### PR TITLE
Bug Fixes

### PR DESCRIPTION
**Pull request by buob**

### CODE REVIEW

**Comment by scottdraves** [comment]
the link clicking fix looks good, but the min-height restriction seems to cause a problem where now every time i render the section, the cells below move up and down briefly.  they go back to the same place at least, but having them jump around is very annoying.  do we need https://github.com/twosigma/beaker-notebook/issues/1475 in order for this to work right?

**Comment by buob** [comment]
Yeah, that fix would also fix the jumping issue, but I think the fix is going to be a lot more complex -- so I just lowered it to 1em instead of what it was before, so the jumping should be gone now until that issue is fixed.

**Comment by scottdraves** [comment]
can the minimum just be the same as the header during edit, then it would not jump at all right?

**Comment by buob** [comment]
Yup, that's what the update I just pushed reset it to.

**Pull request merged**
