### PR TITLE
fix plots need more lines #2029

### PR DESCRIPTION
**Pull request by kpaharelau**
Algorithm for calculation time increment has been fully changed. Use notebook for tests - https://www.dropbox.com/s/xwiz4max5htq83e/2029.bkr?dl=0

### CODE REVIEW

**Comment by kpaharelau** [comment]
I went for lunch and found that the new algorithm is nonsense :-( . I will change it Please not review

**Comment by kpaharelau** [comment]
I made predefined time values more detailed. It should solve all problems with gridlines

**Comment by kpaharelau** [comment]
This is a correct link for the test notebook 
 https://www.dropbox.com/s/xwiz4max5htq83e/2029.bkr?dl=0

**Comment by scottdraves** [comment]
Thanks.
This is a step in the right direction.  But still, the lines are never closer than about 104 pixels.
can you make them go down to 50?

**Comment by scottdraves** [comment]
:+1:

**Pull request merged**
