### PR TITLE
Configure sql connection with environment variable.

### PR DESCRIPTION
**Pull request by jdavidheiser**
This adds the ability to define the default SQL connections string using an environment variable.  This seemed to be more in-line with how other Jupyter configuration is handled, and mirrors `BEAKER_JDBC_DRIVER_LIST` from `JDBCclient.java`

Addresses #7518

### CODE REVIEW

**Comment by scottdraves** [comment]
awesome, thank you, can you please send us a signed CLA? https://github.com/twosigma/beakerx/blob/master/CONTRIBUTING.md#pull-requests

**Comment by jdavidheiser** [comment]
Just sent the CLA.

**Comment by scottdraves** [comment]
thanks, will test this shortly.

**Comment by scottdraves** [comment]
🐬

**Comment by dclong** [comment]
Great work! Is there any tutorial on this? I check notebooks on SQL in the doc directory but didn't find one.

**Comment by scottdraves** [comment]
thx I added a note in the SQL doc about the envar.

**Comment by dclong** [comment]
@scottdraves Can you be more specific about what string should be set for the env variable `BEAKERX_SQL_DEFAULT_JDBC`?

BTW, is it possible to configure database connections via configuration files? This is a little bit safer than having plain passwords in notebooks.

**Comment by jdavidheiser** [comment]
@dclong you can set up a JSON kernelspec wherever your Jupyter install is keeping them (ie `/opt/conda/share/jupyter/kernels/kernel_name/kernel.json` if you're using a standard Anaconda install)

The contents of the file should be something like this:

```{
  "argv": [
    "java", "-cp", "/opt/conda/lib/python3.6/site-packages/beakerx/kernel/base/lib/*:/opt/conda/lib/python3.6/site-packages/beakerx/kernel/sql/lib/*", "com.twosigma.beakerx.sql.kernel.SQL",  "{connection_file}"
  ],
    "display_name": "Postgres",
  "language": "SQL",
  "env": {
      "PS1": "Postgres",
      "BEAKERX_SQL_DEFAULT_JDBC": "jdbc:postgresql://some_url:port_number/database_name?user=username&password=password"
  }
}
```


The exact paths to the JARs will depend on your Beaker install - you can copy them out of an existing Kernel JSON that the Beaker installer already set up for you.

For the environment variable, you just need to look up the JDBC URL format for the database jdbc driver you're using - some take different options, or call username and password something different.

**Comment by dclong** [comment]
@jdavidheiser Thank you very much! This is very helpful.

1. Is there a magic associated with the new kernel (say, %%postgres) created?
2. Is there any way to create databases (to be used in the SQL kernel) instead of creating new Kernels?

**Comment by jdavidheiser** [comment]
It’s a new kernel. Magic functions work totally differently.

**Pull request merged**
