### PR TITLE
enable ipython test

### PR DESCRIPTION
**Pull request by EfimovVladimir**

### CODE REVIEW

**Comment by EfimovVladimir** [comment]
kick jenkins

**Comment by EfimovVladimir** [comment]
kick jenkins

**Comment by scottdraves** [comment]
kick jenkins

**Comment by scottdraves** [comment]
kick jenkins

**Comment by scottdraves** [comment]
kick jenkins

**Comment by scottdraves** [comment]
kick jenkins

**Comment by scottdraves** [comment]
the server looks good now @EfimovVladimir please bring up to date with master

**Comment by scottdraves** [comment]
kick jenkins

**Pull request merged**
