### PR TITLE
GroovyEvaluator without groovy shell, environment variables in groovy…

### PR DESCRIPTION
**Pull request by dkobylarz**
this PR contains all vital ai updates to groovy evaluator:
- no groovy shell, all the code is compiled by groovy classloader
- groovy classpath and output directory may contain environment variables - this is extremely useful for bkr files portability
- friendly error message when groovy not found when using GROOVY_JAR_PATH env variable ( this is a subject of another PR #3416

### CODE REVIEW

**Comment by scottdraves** [comment]
i tried this branch and when I opened the chartingTutorial.bkr, the initialization cells fail.
I get "Error  ... cancelled!" from simple code like `rates.size()` in this notebook.

**Comment by dkobylarz** [comment]
I have just fixed the error handler and added a binding object to share variables in groovy context. It's been tested with chartingTutorial.bkr and groovy.bkr files

**Comment by hadfield** [comment]
hi scott - any reason we're getting the message "All checks have failed" message?

**Comment by tomca32** [comment]
@hadfield seems to be a problem with our build, not with the code

**Comment by tomca32** [comment]
kick jenkins

**Comment by hadfield** [comment]
ok, thanks @tomca32

**Comment by tomca32** [comment]
kick jenkins

**Comment by tomca32** [comment]
build is passing now

**Comment by scottdraves** [comment]
thanks this is looking good will continue to test.

**Comment by scottdraves** [comment]
the first cell of groovy-examples.bkr in the tutorial fails like this:
https://pub.beakernotebook.com/#/publications/56b4919a-8910-4691-b2fc-aa456b43ab56

**Comment by dkobylarz** [comment]
this cell fails as the correct import should be `static java.lang.Math.*`. Master branch version accidentally works in groovy shell as it somehow prepends java.lang package. I can update that groovy-example.bkr file or have a special rule for static Math.\* import but I think the latter is a bad idea

**Comment by scottdraves** [comment]
thank you!

**Pull request merged**
