### PR TITLE
gulp work

### PR DESCRIPTION
**Pull request by samccone**
cleanups and simplifications to the gulp file that I cam across while working on the file.

### CODE REVIEW

**Comment by ildipo** [comment]
looks good

**Comment by mforsyth** [comment]
Awesome work... as I mentioned let's just make sure to test with runembed task first .

**Comment by samccone** [comment]
I think this is the PR in question @mforsyth https://github.com/twosigma/beaker-notebook/pull/1723

**Comment by mforsyth** [comment]
Ahh, you are right @samccone

**Pull request merged**
