### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by ReadmeCritic**
Created with https://github.com/dkhamsing/frankenstein

### CODE REVIEW

**Comment by scottdraves** [comment]
we would need a CLA... possible?

**Comment by ReadmeCritic** [comment]
Sure let me know the info

**Comment by scottdraves** [comment]
See the section "Contributing to Beaker" http://beakernotebook.com/community

**Comment by ReadmeCritic** [comment]
Sent

**Comment by scottdraves** [comment]
thanks!  however the branch from with the PR came has been deleted... I still see the diff so I could make an identical edit myself but I would prefer you got credit.  can you make a new one or should I copy?

**Comment by ReadmeCritic** [comment]
New one #2922

**Pull request closed without merging**
