### PR TITLE
delete beakerxTest dirs

### PR DESCRIPTION
**Pull request by EfimovVladimir**

### CODE REVIEW

**Comment by EfimovVladimir** [comment]
#6362

**Comment by scottdraves** [comment]
this looks like it will solve the problem but wouldn't it be better to call this function in the right place?
https://github.com/twosigma/beakerx/blob/356cf950582b9c79d68c29eab7eca1a9d8476bf2/kernel/base/src/main/java/com/twosigma/beakerx/evaluator/BaseEvaluator.java#L189
this might not be a test problem.  are the directories leaking even from normal usage?

**Comment by scottdraves** [comment]
@jaroslawmalekcodete

**Comment by jaroslawmalekcodete** [comment]
Instead of adding task to build.gradle (which should work of course but only for test run from console) we can try to add `path.toFile().deleteOnExit()` below https://github.com/twosigma/beakerx/blob/master/kernel/base/src/test/java/com/twosigma/beakerx/evaluator/EvaluatorTest.java#L70

**Pull request merged**
