### PR TITLE
Add MathJax capabilities to Markdown Cells

### PR DESCRIPTION
**Pull request by buob**

### CODE REVIEW

**Comment by scottdraves** [comment]
need to use ptsans while editing the markdown too not just displaying it.

**Comment by scottdraves** [comment]
also this introduces a bug where if you keep clicking on the editor it just keeps getting bigger and bigger.

**Comment by buob** [comment]
markdown mov

I'm not seeing the issue you're describing, could you give me a little more info?

(this is passing locally)

**Comment by buob** [comment]
Tabling until after v1.2; the epiceditor dependency isn't as flexible as we need it to be

**Pull request closed without merging**
