### PR TITLE
plot of horizontal line broken (#1459)

### PR DESCRIPTION
**Pull request by mnavasiolava**
Wide datarange when all ys/xs are the same. Works both for point and lines

### CODE REVIEW

**Comment by scottdraves** [comment]
:+1:

**Comment by ildipo** [comment]
:+1:

**Comment by mnavasiolava** [comment]
not vs, it just was made in different place to make it work both for points and lines.
"daterange.yl - daterange.yl / 10" means that we want to widen the range with the value 10 times lower than the initial yl

**Comment by samccone** [comment]
ok, I am just trying to understand how this fixes it :)

Thanks for explaining!

**Pull request merged**
