### PR TITLE
fix 404 error for image, close Issue #1618

### PR DESCRIPTION
**Pull request by kpaharelau**

### CODE REVIEW

**Comment by samccone** [comment]
hey @kpaharelau thanks for the PR, can you describe how I can reproduce this issue / verify that it has fixed the issue?

**Comment by kpaharelau** [comment]
Hi. You can try to upload  /core/config/tutorials/chartingTutorial.bkr file (File->Upload(.bkr)).  You will see 404 error in console log. The problem is in the gulpfile.js. Some vendor's image files did not get into the assembly. The problem disappears after applying my changes

**Comment by samccone** [comment]
cool thanks @kpaharelau 

Wondering if it might be more appropriate to move this copy task into
https://github.com/twosigma/beaker-notebook/blob/master/core/build.gradle#L108

Since we are already copying vendor files in our gradle task

**Comment by kpaharelau** [comment]
Interesting :-). I will analyze the problem.

**Comment by kpaharelau** [comment]
Hi, I fixed this problem using gradle. Now I have access to repo and made pull request using branch from it. https://github.com/twosigma/beaker-notebook/pull/1994

**Comment by samccone** [comment]
thanks @kpaharelau 

@spot I think we should be able to close this PR in favor of #1994

**Pull request closed without merging**
