### PR TITLE
#5799 Python plots won't work with pandas Series

### PR DESCRIPTION
**Pull request by rbidas**

### CODE REVIEW

**Comment by rbidas** [comment]
It also covers issue #5822 
https://github.com/twosigma/beakerx/issues/5822

**Comment by scottdraves** [comment]
great thx please add an example of plotting a Series to pythonChartingAPI.ipynb

**Comment by rbidas** [comment]
Example added

**Comment by scottdraves** [comment]
thanks that looks perfect, but it looks like the changes from my commit were lost: https://github.com/twosigma/beakerx/pull/5885/commits/d888e4dc37112e32b5ba5f137b080c4db85909bf
please check your merge...

**Pull request merged**
