### PR TITLE
#4605 Null handling in JavaScript cell output

### PR DESCRIPTION
**Pull request by sluhtoja**

### CODE REVIEW

**Comment by scottdraves** [comment]
kick jenkins

**Comment by scottdraves** [comment]
this looks like the right idea, but it prints "Undefined" instead of null.
And for values that really are undefined, it should not show any result.
screen shot 2016-08-17 at 10 44 17 am

**Comment by scottdraves** [comment]
also, i still don't understand what "//noinspection JSUnresolvedVariable" does...

**Comment by sluhtoja** [comment]
Intellij is giving an error on the variable define. Basically it is supressing an Intellij based error.
Will remove it.

**Comment by scottdraves** [comment]
👍

**Pull request merged**
