### PR TITLE
#6691 add autoZoom support to CombinedCharts

### PR DESCRIPTION
**Pull request by markhalonen**

### CODE REVIEW

**Comment by markhalonen** [comment]
This code should've been in #6575, I overlooked it.

**Comment by scottdraves** [comment]
thank you, but i wasn't able to get this to work on a combined plot.
can you post the exact code you ran, and how you interacted with it?

**Comment by markhalonen** [comment]
If you were trying to use `autoZoom` with Python `CombinedChart`'s that wasn't working. I have fixed that in d198ea9

So the original PR (#6608) added `autoZoom` to regular charts. `CombinedChart`'s do not inherit from regular charts, so `autoZoom` had to added for `CombinedChart`'s in this PR

**Comment by markhalonen** [comment]
And then it should work just like any other chart option: `cplot = CombinedPlot(xLabel= "Linear", autoZoom=True)`

**Pull request merged**
