### PR TITLE
Ambiance: modularizing css

### PR DESCRIPTION
**Pull request by alice-kroch**
Please, review the code

### CODE REVIEW

**Comment by tomca32** [comment]
OK, so no more fixed values in that file, I like that. Could we move all the rules into a separate file called theme.scss or basetheme.scss. Then this file would have only the color definitions and one rule saying something like .ambiance-theme extends .base-theme (or whatever the sass syntax is for extending)

That way all theme files would just have different color definitions and would be really easy to manage. I'm pretty confident that this is possible with sass since it can import and extend rules: http://sass-lang.com/documentation/file.SASS_REFERENCE.html

**Comment by scottdraves** [comment]
right, the goal is to define a new theme with a file that has just 10-15 color definitions.

**Comment by alice-kroch** [comment]
Updated. Please, check this approach

**Comment by tomca32** [comment]
Modularization looks good. We'll have to update it with additional css changes that were added to master in the meantime.

**Comment by scottdraves** [comment]
please bring this up to date with master

**Comment by tomca32** [comment]
There are some totally new properties in the ambiance scss file like cursor image on various elements that need to be included.

**Comment by alice-kroch** [comment]
Updated. Please, check.

**Comment by scottdraves** [comment]
markdown blockquote fix has been lost it seems.

**Comment by alice-kroch** [comment]
Fixed.

**Comment by scottdraves** [comment]
kick jenkins

**Comment by scottdraves** [comment]
:dolphin:

**Comment by alice-kroch** [comment]
Up to date with master. Please, check.

**Pull request merged**
