### PR TITLE
Replace cmd commands for new notebook commands

### PR DESCRIPTION
**Pull request by alice-kroch**
Issue #3632. Please, check.

### CODE REVIEW

**Comment by kpaharelau** [comment]
kick jenkins

**Comment by scottdraves** [comment]
OK this looks good but I realized it's also broken on Windows, but it has the opposite problem.
There, control-N just opens a new browser, so we can't use it for new notebook.
On Windows it should be Alt-N and Shift-Alt-N

**Comment by alice-kroch** [comment]
Updated. Please, check.

**Comment by scottdraves** [comment]
:+1:

**Comment by kpaharelau** [comment]
kick jenkins

**Comment by kpaharelau** [comment]
kick jenkins

**Pull request merged**
