### PR TITLE
fix e2e test errors

### PR DESCRIPTION
**Pull request by EfimovVladimir**

### CODE REVIEW

**Comment by scottdraves** [comment]
no apparent change in behavior for me....

**Comment by EfimovVladimir** [comment]
#6542

**Comment by EfimovVladimir** [comment]
ChromeDriver 2.34 Supports Chrome v61-63

**Comment by scottdraves** [comment]
the funny tab does not open but now 11 tests are failing:
```


158 passing (1395.90s)
11 failing

1) IntSlider widgetsuite2 Cell output contains "50":
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
running chrome
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

2) IntSlider widgetsuite2 Cell output contains "horizontal":
Failed: Promise was rejected with the following reason: java.net.SocketException: Connection reset
running chrome
Error: Promise was rejected with the following reason: java.net.SocketException: Connection reset
    at BeakerXPageObject.runCallToGetOutputText (tests/beakerx.po.js:94:16)
    at BeakerXPageObject.runCallAndCheckOutputText (tests/beakerx.po.js:83:27)
    at UserContext.<anonymous> (tests/groovy/javaWidgetsTest.js:60:17)
    at elements("i.kernel_idle_icon") - isEnabled.js:18:17
    at isEnabled("i.kernel_idle_icon") - waitForEnabled.js:73:22

3) IntProgress widgetsuite3 Widget value = 110:
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
running chrome
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

4) IntProgress widgetsuite3 Cell output contains "50":
Failed: Promise was rejected with the following reason: java.net.SocketException: Connection reset
running chrome
Error: Promise was rejected with the following reason: java.net.SocketException: Connection reset
    at BeakerXPageObject.runCallToGetOutputText (tests/beakerx.po.js:94:16)
    at BeakerXPageObject.runCallAndCheckOutputText (tests/beakerx.po.js:83:27)
    at UserContext.<anonymous> (tests/groovy/javaWidgetsTest.js:90:17)
    at elements("div.output_subarea.output_text") - isVisible.js:54:17
    at isVisible("div.output_subarea.output_text") - waitForVisible.js:73:22

5) Run cell with textsuite11 Plot has 8 text elements:
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
running chrome
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

6) Run cell with crosshairsuite12 Plot has crosshair:
Failed: Promise was rejected with the following reason: java.net.SocketException: Connection reset
running chrome
Error: Promise was rejected with the following reason: java.net.SocketException: Connection reset
    at element("#svgg") - $.js:42:17
    at $("#svgg") - at UserContext.<anonymous> (tests/groovy/plotGroovyTest.js:151:18)

7) Run "Second Y Axis" cellsuite14 Plot has second Y Axis:
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
running chrome
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

8) Run "Logarithmic Scale" cellssuite15 Plot has 2 lines:
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
running chrome
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

9) Simple Time Plotsuite5 Time Plot has millisecond resolution:
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
running chrome
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

10) Simple Time Plotsuite5 Time Plot has nanosecond resolution:
Failed: Promise was rejected with the following reason: java.net.SocketException: Connection reset
running chrome
Error: Promise was rejected with the following reason: java.net.SocketException: Connection reset
    at UserContext.<anonymous> (tests/python/plotPythonTest.js:153:18)
    at elements("i.kernel_idle_icon") - isEnabled.js:18:17
    at isEnabled("i.kernel_idle_icon") - waitForEnabled.js:73:22

11) Second Y Axissuite6 Plot has second Y Axis:
Failed: Promise was rejected with the following reason: java.net.SocketException: Connection reset
running chrome
Error: Promise was rejected with the following reason: java.net.SocketException: Connection reset
    at UserContext.<anonymous> (tests/python/plotPythonTest.js:164:18)
    at elementIdEnabled("0.9200823140758883-1038") - isEnabled.js:35:53
```

**Comment by scottdraves** [comment]
🐬 🐬

**Pull request merged**
