### PR TITLE
#2524  sql should not require %%inputs %%outputs

### PR DESCRIPTION
**Pull request by maksim-lauryk**
#2524  sql should not require %%inputs %%outputs

updated, now %%inputs %%outputs are not required

### CODE REVIEW

**Comment by ildipo** [comment]
looks good, just remove commented code please

**Comment by scottdraves** [comment]
screen shot 2015-09-29 at 8 31 40 am

produces stack trace

```
ep 29, 2015 8:31:32 AM com.twosigma.beaker.sqlsh.utils.SQLEvaluator$MyRunnable run
SEVERE: null
java.lang.RuntimeException: name is illegal for notebook namespace: 'colorTable '
    at com.twosigma.beaker.NamespaceClient.set4(NamespaceClient.java:150)
    at com.twosigma.beaker.NamespaceClient.set(NamespaceClient.java:158)
```

**Comment by scottdraves** [comment]
similar problem with this error:
screen shot 2015-09-29 at 8 33 52 am

**Comment by maksim-lauryk** [comment]
If you mean a format of errors outputting, Yes, it will be improved, I'm working on it in other branch.

**Comment by maksim-lauryk** [comment]
commented code removed

**Pull request merged**
