### PR TITLE
js syntax stack

### LINKED ISSUE #1865: javascript syntax error stack trace is bad
screen shot 2015-06-30 at 10 23 22 am

### PR DESCRIPTION
**Pull request by samccone**
Handle acorn parsing errors. Fixes #1865

### CODE REVIEW

**Comment by scottdraves** [comment]
screen shot 2015-07-10 at 2 36 11 pm

**Comment by samccone** [comment]
Ha well that is unexpected 😜

**Comment by samccone** [comment]
oh i understand now, @scottdraves I think your output cell was collapsed

**Comment by scottdraves** [comment]
nope

**Comment by samccone** [comment]
all fixed, old cached version in my browser and typo :)

**Pull request merged**
