### PR TITLE
#5971 Remove duplicated functionality between setup.py and beakerx-install  

### PR DESCRIPTION
**Pull request by rbidas**
Covers also task #5781 3 copies of the jars

### CODE REVIEW

**Comment by scottdraves** [comment]
worked well as a developer, but then i made a test src package for pip (following instructions in RELEASE.md) up to but not including `pip install twine`.  Then went to test.  I created a new env, did `pip install dist/beakerx-*.tar.gz` and it worked, then `beakerx-install` and it failed:
```
$ beakerx-install
Installing /Users/spot/anaconda/envs/testx/lib/python3.6/site-packages/beakerx/static -> beakerx
Symlinking: /Users/spot/anaconda/envs/testx/share/jupyter/nbextensions/beakerx -> /Users/spot/anaconda/envs/testx/lib/python3.6/site-packages/beakerx/static
- Validating: OK

    To initialize this nbextension in the browser every time the notebook (or other app) loads:

          jupyter nbextension enable beakerx --py --sys-prefix

Enabling notebook extension beakerx/extension...
      - Validating: OK
Traceback (most recent call last):
  File "/Users/spot/anaconda/envs/testx/bin/beakerx-install", line 11, in <module>
    sys.exit(install())
  File "/Users/spot/anaconda/envs/testx/lib/python3.6/site-packages/beakerx/install.py", line 171, in install
    _install_beakerx(args)
  File "/Users/spot/anaconda/envs/testx/lib/python3.6/site-packages/beakerx/install.py", line 159, in _install_beakerx
    _install_kernels()
  File "/Users/spot/anaconda/envs/testx/lib/python3.6/site-packages/beakerx/install.py", line 84, in _install_kernels
    for kernel in _all_kernels():
  File "/Users/spot/anaconda/envs/testx/lib/python3.6/site-packages/beakerx/install.py", line 34, in _all_kernels
    'beakerx', 'kernel')
  File "/Users/spot/anaconda/envs/testx/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1239, in resource_listdir
    resource_name
  File "/Users/spot/anaconda/envs/testx/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1499, in resource_listdir
    return self._listdir(self._fn(self.module_path, resource_name))
  File "/Users/spot/anaconda/envs/testx/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1589, in _listdir
    return os.listdir(path)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/spot/anaconda/envs/testx/lib/python3.6/site-packages/beakerx/kernel'
```

**Comment by scottdraves** [comment]
```
$ ls -F /Users/spot/anaconda/envs/testx/lib/python3.6/site-packages/beakerx
__init__.py             beakerx_widgets.py      groovy_magic.py         output_container/       static/
__pycache__/            bkr2ipynb.py            install.py              plot/                   tabledisplay/
_version.py             easyform/               kernel_spec.py          runtime.py              utils.py
```

**Comment by scottdraves** [comment]
The jars are missing from the package: 
```
tar tfvz beakerx/dist/beakerx-0.6.2.tar.gz  | grep jar
```
shows nothing.

**Comment by rbidas** [comment]
Done

**Pull request merged**
