### PR TITLE
#6207: [%classpath add mvn ... ] change ivy to mvn

### PR DESCRIPTION
**Pull request by jaroslawmalekcodete**

### CODE REVIEW

**Comment by scottdraves** [comment]
kick jenkins

**Comment by scottdraves** [comment]
kick jenkins

**Comment by scottdraves** [comment]
```
:base:test

com.twosigma.beakerx.kernel.commands.ClasspathAddMvnDepsMagicCommandTest > unresolvedDependency FAILED
    java.lang.AssertionError at ClasspathAddMvnDepsMagicCommandTest.java:96
```
How can we get some logging to debug this?  What is the value of `text`?

**Comment by jaroslawmalekcodete** [comment]
kick jenkins

**Comment by jaroslawmalekcodete** [comment]
please change jenkins build configuration from  ```gradle build``` to  ```gradle build -i```

**Comment by jaroslawmalekcodete** [comment]
from jenkins build test log
unresolveddependencytest
and the error is from 
https://github.com/twosigma/beakerx/blob/jarek/replace_ivy_to_mvn/kernel/base/src/main/java/com/twosigma/beakerx/kernel/commands/MavenJarResolver.java#L95

**Comment by scottdraves** [comment]
i added the -i

**Comment by scottdraves** [comment]
kick jenkins

**Comment by scottdraves** [comment]
OK i installed mvn on the right machine this time

**Comment by scottdraves** [comment]
no! i am baffled

**Comment by scottdraves** [comment]
kick jenkins

**Comment by scottdraves** [comment]
OK next step: print out the PATH and the contents of /usr/local/bin.
mvn is installed there and I am sure it's the right server now.

**Comment by scottdraves** [comment]
kick jenkins

**Comment by scottdraves** [comment]
```
+ which mvn
/usr/local/bin/mvn
+ gradle build -i
Starting Build
```
and yet still `No mvn found`

https://stackoverflow.com/questions/26609922/maven-home-mvn-home-or-m2-home

**Comment by scottdraves** [comment]
kick jenkins

**Comment by scottdraves** [comment]
```
+ mvn --version
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T07:58:13Z)
Maven home: /home/ubuntu/apache-maven-3.5.2
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-135-generic", arch: "amd64", family: "unix"
+ gradle build -i
Starting Build
```

**Pull request merged**
