### PR TITLE
Wrong encoding on import of non-ascii .bkr file #2733

### PR DESCRIPTION
**Pull request by mnavasiolava**

### CODE REVIEW

**Comment by scottdraves** [comment]
:+1:

**Comment by scottdraves** [comment]
This looks good but it actually shows a problem if I import notebooks such as
https://pub.beakernotebook.com/#/publications/560b54da-3c14-4890-8b64-b204bc798320?fullscreen=false or
https://pub.beakernotebook.com/#/publications/560c510c-16a8-4a22-9bed-93071e9f88e8?fullscreen=false
The former has some chinese characters, and the latter has some non-breaking spaces.
The chinese characters appear as ? and the space as �.  So maybe we are not encoding correctly when we save?

**Comment by mnavasiolava** [comment]
You are right, downloaded notebooks are not encoded correctly, and that's why they are opened with ?? symbols

**Comment by scottdraves** [comment]
:+1:

**Pull request merged**
