### PR TITLE
PR for issue #4404 "Use bkHelper.httpPost(...) instead of $.ajax(...)" 

### PR DESCRIPTION
**Pull request by konstantinTarletski**
…POST was chainged

### CODE REVIEW

**Comment by konstantinTarletski** [comment]
There are stay several "$.ajax(...)" , but I am not shure taht I should redo they also:
some of the are GET, another do not have access to bkHelper.

**Comment by scottdraves** [comment]
looks like node was broken...

**Comment by scottdraves** [comment]
kick jenkins

**Comment by scottdraves** [comment]
kick jenkins

**Pull request merged**
