### PR TITLE
#6809 sections of options should use tabs

### PR DESCRIPTION
**Pull request by piorek**

### CODE REVIEW

**Comment by scottdraves** [comment]
cool this looks good but there are some glitches:
1) when i first click on the "BeakerX" tab the JVM options are not appearing:
screen shot 2018-02-21 at 11 26 42 am
i have to click on the JVM options tab header for them to appear (or click on the UI tab and then back to JVM).
2) now that the title "JVM Options" appears in the tabs, no need to repeat it in the contents.  ditto for "UI Options".

**Comment by piorek** [comment]
Should be OK now

**Comment by scottdraves** [comment]
Thanks that worked but please address:

> now that the title "JVM Options" appears in the tabs, no need to repeat it in the contents. ditto for "UI Options".

that also means eliminating the ruler line that goes with the heading.

**Comment by piorek** [comment]
Done

**Comment by scottdraves** [comment]
Thanks, that's that's good but I still see a couple of problems:
1) only show the "Result: java ...." line (including the sync symbol) in the JVM options panel.
2) the panel contents are truncating the descenders (the "p") in the text of the labels:
screen shot 2018-02-24 at 3 37 58 pm

**Comment by piorek** [comment]
done

**Pull request merged**
