### PR TITLE
#3688. API to load another notebook

### PR DESCRIPTION
**Pull request by sshkalikov**
added loadLibrary(url) method returning promise to beaker object **only for js**
can add it for other languages, too, but it won't be reliable

### CODE REVIEW

**Comment by scottdraves** [comment]
didn't work for me.  is there a demo?  maybe i did it wrong.
i created a notebook with a groovy cell that just had one cell

```
x = 10
```

and saved it as ~/lib.bkr.

then i made a new notebook with a JS cell that said

```
beaker.loadLibrary("file:/Users/spot/lib.bkr")
```

and evaluated it and got the following console errors:

```
beakerVendor.js:62726 TypeError: Cannot read property 'type' of null
    at Object.bkHelper.receiveEvaluationUpdate (beakerApp.js:3949)
    at output.then.JavascriptCancelFunction (:8801/3c7a203/beaker/plugin/evaluator/javaScript.js:300)
    at processQueue (beakerVendor.js:65042)
    at beakerVendor.js:65058
    at Scope.$eval (beakerVendor.js:66310)
    at Scope.$digest (beakerVendor.js:66126)
    at Scope.$apply (beakerVendor.js:66418)
    at done (beakerVendor.js:60756)
    at completeRequest (beakerVendor.js:60954)
    at XMLHttpRequest.requestLoaded (beakerVendor.js:60895)(anonymous function) @ beakerVendor.js:62726
beakerVendor.js:62726 TypeError: Cannot read property 'update_id' of null
    at beakerApp.js:9859
    at Scope.$digest (beakerVendor.js:66154)
    at Scope.$apply (beakerVendor.js:66418)
    at done (beakerVendor.js:60756)
    at completeRequest (beakerVendor.js:60954)
    at XMLHttpRequest.requestLoaded (beakerVendor.js:60895)
```

**Comment by sshkalikov** [comment]
Sounds like you're doing everything as designed, so there's my fail. Maybe
this one cell of lib.bkr is not init cell?

**Comment by scottdraves** [comment]
right i forgot to set that.
so if no such cells should do nothing not crash.

**Comment by scottdraves** [comment]
cool, when I set the init cell, it worked! 🐬 

but: looks like it returns an array of the values from the cells.
instead, it should just print the names of the libraries as they are loaded recursively,
and ideally have a progress meter for evaluating the cells within each library.
return value should be just be a string that reports the total number of cells evaluated in each language.

also, if i didn't already have the language loaded and the notebook has cells in another language, then i got an error.  there are two options to fix this:
either start that language, or skip the cells.
i can see arguments for both but i think starting the language is the simpler for users to understand, so let's start with that.

**Comment by scottdraves** [comment]
more serious problem: the 2nd time I run a cell with loadLibrary(), it crashes:

```
beakerVendor.js:62726 TypeError: Cannot read property 'type' of null
    at Object.bkHelper.receiveEvaluationUpdate (beakerApp.js:3949)
    at output.then.JavascriptCancelFunction (javaScript.js:300)
    at processQueue (beakerVendor.js:65042)
    at beakerVendor.js:65058
    at Scope.$eval (beakerVendor.js:66310)
    at Scope.$digest (beakerVendor.js:66126)
    at Scope.$apply (beakerVendor.js:66418)
    at beakerVendor.js:68243
    at completeOutstandingRequest (beakerVendor.js:55294)
    at beakerVendor.js:55571(anonymous function) @ beakerVendor.js:62726(anonymous function) @ beakerVendor.js:59455processQueue @ beakerVendor.js:65050(anonymous function) @ beakerVendor.js:65058Scope.$eval @ beakerVendor.js:66310Scope.$digest @ beakerVendor.js:66126Scope.$apply @ beakerVendor.js:66418(anonymous function) @ beakerVendor.js:68243completeOutstandingRequest @ beakerVendor.js:55294(anonymous function) @ beakerVendor.js:55571
beakerVendor.js:62726 TypeError: Cannot read property 'update_id' of null
    at beakerApp.js:9859
    at Scope.$digest (beakerVendor.js:66154)
    at Scope.$apply (beakerVendor.js:66418)
    at beakerVendor.js:68243
    at completeOutstandingRequest (beakerVendor.js:55294)
    at beakerVendor.js:55571
```

**Comment by sshkalikov** [comment]
now it prints path to library that being loaded, starts missing evaluators and returns number of executed cells
just in case, [there're my test notebooks ](https://www.dropbox.com/sh/9g7t4glf62atl1o/AAB_2nFvQ1pCrfRCr5kytcqxa?dl=0)
also fixed bug with second run and bug with loading notebook without initialization cells

**Comment by scottdraves** [comment]
calling it repeatedly like this:

```
beaker.loadLibrary("/Users/spot/libxasdf.bkr");
beaker.loadLibrary("/Users/spot/lib2.bkr");
```

doesn't really work because the 2nd load does not wait for the 1st to finish.  in fact, it should probably give an error.  we could have users .then everything but i think we should just allow this function to take a list:

```
beaker.loadLibrary(["/Users/spot/libxasdf.bkr",
                               "/Users/spot/lib2.bkr"]);
```

also, there seems to be a caching problem.  if you load a notebook, then edit and save that notebook, and then load it again, you get the old version.  this would make development really hard.

another weirder problem:
say you have a notebook with just JS in it.  you use this JS cell to load a notebook with groovy.
groovy is loaded.  you then create a groovy cell.  then save the notebook & open.
the groovy cells never resolve because groovy was not added to the notebook model.

**Comment by scottdraves** [comment]
and please bring up to date with master.

**Pull request merged**
