### PR TITLE
Strings with double slash ("//"), e.g., URLs, broken in Java language…

### PR DESCRIPTION
**Pull request by kpaharelau**
… cells #3449

Problem was un the not correct comments removing.

We had after code normalizing

public class Test {
  public static void main(String[] argv) {
    String url = "http:
    System.out.println("--- Bug not found ---");
  }
}
'

I have added function 'removeComments' instead regex processing

### CODE REVIEW

**Comment by scottdraves** [comment]
:+1:

**Comment by tomca32** [comment]
Java Enums are pretty much classes, right?

Isn't it better then to have the enums have a method to do all this logic rather then switching the enum from the outside? It seems to me that would be more maintainable and cleaner.

Not a Java guy really so I might be talking crap.

**Comment by scottdraves** [comment]
this code is copy-and-pasted from stackoverflow, changes are likely to just introduce bugs.

**Comment by scottdraves** [comment]
fails on this:

```
String foo = "\\" + // comment
  "\\";
```

would also fail on a unicode escape.

**Comment by scottdraves** [comment]
how about https://pub.beakernotebook.com/#/publications/56bc9b29-2439-437e-ae61-815fdc9d95e7

**Comment by scottdraves** [comment]
the error is actually correct
:+1:

**Comment by scottdraves** [comment]
still, just keeping track of 2 chars of history is inadequate.  what can you learn from this?
https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/ast/comments/CommentsParser.java

**Comment by scottdraves** [comment]
:+1:

**Pull request merged**
