### PR TITLE
#4750 - List of objects not displaying as table - Javascript version

### PR DESCRIPTION
**Pull request by dmtrius**

### CODE REVIEW

**Comment by scottdraves** [comment]
i'm not seeing a difference between master and this branch evaluating groovy

```
new groovy.json.JsonSlurper().parseText('[{"a":1,"b":{"c":3}}]')
```

i just get a string both ways.

**Comment by dmtrius** [comment]
You should switch to table view.

**Comment by dmtrius** [comment]
Put this code in a Groovy cell: data = new groovy.json.JsonSlurper().parseText(new URL("http://data.consumerfinance.gov/api/views.json").text)
Run it
You will see the string representation. Click the output cell menu, then Display -> Table

**Comment by scottdraves** [comment]
You are right, It looks great when I switch it, but it should appear as table by default, like the simpler example does.  

I guess whatever code is making that decision needs to be fixed.

**Pull request closed without merging**
