### PR TITLE
Fix non-firing assertions

### PR DESCRIPTION
**Pull request by acq**
Some of the assertions in kernel/base tests were incomplete : the result of the assertion was not checked.
This commit should fix the few I found.

### CODE REVIEW

**Comment by scottdraves** [comment]
thanks!  however in order to merge a PR we need a completed CLA, please see https://github.com/twosigma/beakerx/blob/master/CONTRIBUTING.md

**Comment by acq** [comment]
I would love to but this link is broken : http://beakerx.com/cla.zip

**Comment by scottdraves** [comment]
sorry, my mistake, i fixed the link, it should be http://beakerx.com/static/cla.zip

**Comment by scottdraves** [comment]
Hi @acq would love to merge this, did you find the documents?

**Comment by acq** [comment]
Sorry, I got sidetracked.
You should have just received it

**Comment by scottdraves** [comment]
🐬

**Pull request merged**
