### PR TITLE
Fix vendor script concat bug in debug

### LINKED ISSUE #1384: debug target should not cat vendor js
gradle debug is still gulping the vendor js into beakerVendor.js

in debug mode we should use all the js and css as-is.

### PR DESCRIPTION
**Pull request by samccone**
Fixes #1384

### CODE REVIEW

**Comment by scottdraves** [comment]
i get a ton of errors from this

GET http://127.0.0.1:8801/390ba65/beaker/vendor/bower_components/lodash/dist/lodash.underscore.js 
(index):40 GET http://127.0.0.1:8801/390ba65/beaker/vendor/flotr2/flotr2.js 
(index):42 GET http://127.0.0.1:8801/390ba65/beaker/vendor/bower_components/big.js/big.js 
(index):43 GET http://127.0.0.1:8801/390ba65/beaker/vendor/bower_components/jquery/jquery.js

**Comment by samccone** [comment]
well that is no good, let me see if I can make this happen locally, it seemed to work for me the first time testing again...

**Comment by samccone** [comment]
k seems to all be working for me @scottdraves mind taking this branch for a test run?

**Comment by scottdraves** [comment]
it works :)

but there are some problems:
1) the zip file is big again, i just got it down to 9.4MB and now it's back to 46MB.
2) what is app/temp doing being used?
3) did you native plotting and ipython2/3? there is some tricky use of moment...

**Comment by DiegoAlbertoTorres** [comment]
2) Is it where Sass is putting its generated CSS files?

**Comment by scottdraves** [comment]
yes plus core/src/main/web/app/temp/templates.js looks like the compiled versions of the JST files.
so this directory has generated web sources, it should be called genweb or something, not "temp"
https://github.com/twosigma/beaker-notebook/issues/1389
but that is for another PR

**Comment by samccone** [comment]
Once the test run finishes this should be good to go :clap:

**Comment by scottdraves** [comment]
ok this works great but the doRemove target should delete them at their new location

**Comment by samccone** [comment]
doRemove is now deleting the files :)

**Pull request merged**
