### PR TITLE
Publications log out

### PR DESCRIPTION
**Pull request by grin**
Implements https://github.com/twosigma/beaker-notebook/issues/2194

### CODE REVIEW

**Comment by grin** [comment]
seems like gravatar module can't be loaded on Travis...though it's working for me locally. Isn't 5edfa11 enough to add a bower component ?

**Comment by samccone** [comment]
you need to vendor `angular-gravatar.js` @grin :)

**Comment by grin** [comment]
yeah, that's weird when I'm running `gradle updatePackages` that file isn't being added now :/

**Comment by grin** [comment]
nv, it's being added...just ignored in git

**Comment by grin** [comment]
updated :green_apple:

**Pull request merged**
