### PR TITLE
#8269: add java11 kernel

### PR DESCRIPTION
**Pull request by jaroslawmalekcodete**

### CODE REVIEW

**Comment by EfimovVladimir** [comment]
needs docs implementing
image

fixed

**Comment by EfimovVladimir** [comment]
see test/ipynb/scala/ChartingTest.ipynb notebook for constructor of TreeMap
image


fixed

**Comment by EfimovVladimir** [comment]
translation to java retutn null
see test/ipynb/groovy/GeneralAutotranslationTest.ipynb
image

it was fixed by new syntax
image

**Comment by EfimovVladimir** [comment]
error: class java.util.List is not a value
see test/ipynb/scala/PlotScalaTest.ipynb notebook
image

fixed

**Comment by EfimovVladimir** [comment]
doesn't work autocomplete on java kernel:

image

**Comment by jaroslawmalekcodete** [comment]
> doesn't work autocomplete on java kernel:
> 
> image

Autocomplete in Java11 kernel is based on autocomplete from jshell, and it looks like it doesn't support autocomplete for java key words like: "impl", "interfa" or "clas" so we'll have to create new an issue for it

**Comment by EfimovVladimir** [comment]
tested - all is fine

**Pull request merged**
