### PR TITLE
add setup code, restart, and fix reconnect in python plugins

### PR DESCRIPTION
**Pull request by scottdraves**
Fix Issue #1188 
Fix Issue #1576 
Fix Issue #994

### CODE REVIEW

**Comment by samccone** [comment]
@ildipo looks like the tests broke with the PR, ideally we would like to avoid merging changes that cause the suite to fail.

@scottdraves @ildipo and thoughts as to the nature of the failure?

**Comment by scottdraves** [comment]
did it?  i am seeing green.

**Comment by samccone** [comment]
The last commit seems to be in an error state
screen shot 2015-05-13 at 9 40 21 am

https://travis-ci.org/twosigma/beaker-notebook/builds/62297780

I am going to rerun now just to be sure

**Comment by samccone** [comment]
Oddly enough it seems like master is :green_apple: 
https://travis-ci.org/twosigma/beaker-notebook/builds/62389348

Rerunning, it very well could have been a timeout connecting to an evaluator on the last commit

**Comment by samccone** [comment]
Yay looks like the rebuild worked :green_apple:

**Pull request merged**
