### PR TITLE
#5994 fix comboBox setting value

### PR DESCRIPTION
**Pull request by MariuszJurowicz**

### CODE REVIEW

**Comment by scottdraves** [comment]
i am not seeing sync from kernel to client:
screen shot 2017-10-18 at 1 57 16 pm

**Comment by MariuszJurowicz** [comment]
Fixed

**Comment by scottdraves** [comment]
still not seeing it

**Comment by MariuszJurowicz** [comment]
I have removed some part of the widget as Michael's changes for value in selectWidget are already in master.

**Pull request merged**
