### PR TITLE
dmtrius/4396 - temp tables broken for mssql

### PR DESCRIPTION
**Pull request by dmtrius**

### CODE REVIEW

**Comment by dmtrius** [comment]
kick jenkins

**Comment by dmtrius** [comment]
kick jenkins

**Comment by scottdraves** [comment]
i'm seeing a bunch of output to stdout and stderr that shows up in the tray:

```
Attempting to load ESAPI.properties via file I/O.
ttempting to load ESAPI.properties via file I/O.Attempting to load ESAPI.properties as resource file via file I/O.
```

and

```
System property [org.owasp.esapi.opsteam] is not set
ystem property [org.owasp.esapi.opsteam] is not setSystem property [org.owasp.esapi.devteam] is not set
```

can that be disabled?

**Comment by dmtrius** [comment]
Logging level for ESAPI could be changed.
About `System property [org.owasp.esapi.opsteam] is not set` - that's more harder, I search for the fix, everybody complaints about it, I could try to change logging level.

**Comment by EfimovVladimir** [comment]
build #1918 got error because it had very long initialization cell
image

**Comment by EfimovVladimir** [comment]
kick jenkins

**Comment by EfimovVladimir** [comment]
Also for another failed test (plotActions) we had this screenshot from jenkins 
image

**Comment by EfimovVladimir** [comment]
kick jenkins

**Comment by EfimovVladimir** [comment]
confirmed,  stdout and stderr didn't appear
image

**Comment by scottdraves** [comment]
this is looking good... :)

**Comment by dmtrius** [comment]
kick jenkins

**Pull request closed without merging**
