### PR TITLE
Fix for issue 320

### PR DESCRIPTION
**Pull request by ildipo**
This addresses the issue #320

Added git hash to each url ‘internally’ used by beaker.
Changed all urls to be relative. Used base tag in a auto-generated
index.html.

### CODE REVIEW

**Comment by scottdraves** [comment]
Great.  Did you test this with the --public-server option, ie with the Docker container?

**Comment by scottdraves** [comment]
when this is merged we should create a new issue to turn caching back, ie stop manipulating the http headers to try to disable it.

**Comment by ildipo** [comment]
I did not test with docker. I'll do that ASAP.

**Comment by ildipo** [comment]
Ok I tested it and I found a small issue - I fixed the rules for nginx one again and now works in both cases.

**Pull request merged**
