### PR TITLE
#2647. use stable release of datatables-fixedcolumns

### PR DESCRIPTION
**Pull request by maxyeg**

### CODE REVIEW

**Comment by ildipo** [comment]
:+1:

**Comment by scottdraves** [comment]
looks like this changes the color of the index column header.
can that be avoided?

**Comment by scottdraves** [comment]
:+1:

**Comment by ildipo** [comment]
Actually I think we should override the CSS rather than removing it from the checked in file.
When we update bower component this will be overwritten

**Comment by scottdraves** [comment]
good point davide

**Pull request merged**
