### PR TITLE
publish javadoc for output classes #3525

### PR DESCRIPTION
**Pull request by kpaharelau**
this is final PR

### CODE REVIEW

**Comment by scottdraves** [comment]
1) fix gradle deps so it builds reliably
2) put all the classes into the same javadoc (now there are 4 instances)
3) fix the favicon

**Comment by scottdraves** [comment]
kick jenkins

**Comment by kpaharelau** [comment]
kick jenkins

**Comment by kpaharelau** [comment]
kick jenkins

**Comment by scottdraves** [comment]
OK cool this is getting close.

1) what are these changes to the tests?  if these are unrelated improvements, please make a separate PR & explain what they do.
2) make the doc links open a new window.
3) why do you have to rewrite the html to get the favicon, isn't it picked up automatically from the top level of the server's namespace?
4) make the links open the appropriate class, eg from the Easyform tutorial, clicking the doc link should open the javadoc for the easyform class.
5) internal classes like the *Serializer classes should not be listed.

**Comment by scottdraves** [comment]
gradle clean target should delete core/src/main/web/app/dist/docs

**Comment by scottdraves** [comment]
:+1:

**Pull request merged**
