### PR TITLE
#6475 plot resize thumb missing in lab

### PR DESCRIPTION
**Pull request by piorek**

### CODE REVIEW

**Comment by piorek** [comment]
@scottdraves @mjurowicz-xsolve there were couple issues 

1. when building extension from js/notebook to js/lab/lib 
image files are collected fom styles, but then were not included when publishing extension
fixed by modifing package.json files section

2. url-s generated when building extension are dont contain /lab/static prefix
only way i was able to fix this was by overriding css classes in lab

But that is not a good idea because i had to overwrite css by hand.

I experimented with webpacks `output.publicPath` and with `__webpack_public_path__` but was not able to get it done this way.

**Comment by MariuszJurowicz** [comment]
I think we could get rid of the extra assets and use the `base64-inline-loader` to emit base64 encoded image data inline. It will produce slightly bigger js files.

**Comment by piorek** [comment]
Thanks will try that

**Comment by piorek** [comment]
Done

**Pull request merged**
