### PR TITLE
Mjm/node plugin  ****Review only do not merge****

### PR DESCRIPTION
**Pull request by planetmcd**
@scottdraves 
This is for review only, because it is based on Ubuntu it is not setup to be merged to master.  
I'll try to find a Mac to test it out on minus the Ubuntu commits.

### CODE REVIEW

**Comment by scottdraves** [comment]
thanks, got it, will look at this today.

**Comment by scottdraves** [comment]
the nub:  when i try to evaluate i get an error on beaker console:

```
nginx-stderr>2014/03/07 10:40:53 [error] 4897#0: *6 upstream sent no valid HTTP/1.0 header while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /node/evaluate HTTP/1.1", upstream: "http://127.0.0.1:8807/evaluate", host: "beaker:8801", referrer: "http://beaker:8801/beaker/"
```

**Comment by planetmcd** [comment]
On ubuntu?

**Comment by planetmcd** [comment]
What code did you try?  I've been using:

```
var concat = function(a, b){
  return a + b;
}
var a = "dog";
var b = "cat";
val = concat(a,b);
val;
```

**Comment by scottdraves** [comment]
yes.  when i access node directly with curl, bypassing nginx, i don't get a complete reply:

```
$ curl --verbose -d 2+3 http://127.0.0.1:8807/evaluate
* About to connect() to 127.0.0.1 port 8807 (#0)
*   Trying 127.0.0.1... connected
> POST /evaluate HTTP/1.1
> User-Agent: curl/7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3
> Host: 127.0.0.1:8807
> Accept: */*
> Content-Length: 3
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 3out of 3 bytes
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Date: Fri, 07 Mar 2014 16:18:36 GMT
< Connection: keep-alive
< Transfer-Encoding: chunked
<
* Connection #0 to host 127.0.0.1 left intact
* Closing connection #0
```

**Comment by scottdraves** [comment]
your code works.

**Comment by planetmcd** [comment]
I see the same issue.  Let me try to debug.

**Comment by planetmcd** [comment]
Will open a new PR without the Linux related commits.

**Pull request closed without merging**
