### PR TITLE
TimePlot class should accept java.util.Date #2704

### PR DESCRIPTION
**Pull request by mnavasiolava**
added support of java.util.Date and java.times.LocalDateTime objects for x coordinates of the TimePlot.
examples can be found in the charting tutorial

### CODE REVIEW

**Comment by scottdraves** [comment]
:+1:

**Comment by scottdraves** [comment]
please remove Java8 feature LocalDateTime, that has to wait, sorry.

**Comment by scottdraves** [comment]
You can leave the code for it in, just comment it out, because we'll need this later but if we use a branch i think it will get lost.

**Comment by mnavasiolava** [comment]
done

**Comment by scottdraves** [comment]
:+1:

**Pull request merged**
