### PR TITLE
Handle moving markdown editor up and down

### PR DESCRIPTION
**Pull request by samccone**

### CODE REVIEW

**Comment by scottdraves** [comment]
how is this different from last time?

**Comment by scottdraves** [comment]
if you open a notebook from a file that has a markdown cell you get

Error: Editor isn't loaded
    at EpicEditor.unload (http://127.0.0.1:8801/beaker/vendor/epiceditor/js/epiceditor.js:1219:13)
    at Object.fn (http://127.0.0.1:8801/beaker/app/mainapp/components/notebook/markdowncell-directive.js:106:28)
    at Scope.$digest (http://127.0.0.1:8801/beaker/vendor/bower_components/angular/angular.js:11761:29)
    at Scope.$apply (http://127.0.0.1:8801/beaker/vendor/bower_components/angular/angular.js:12012:24)
    at done (http://127.0.0.1:8801/beaker/vendor/bower_components/angular/angular.js:7818:45)
    at completeRequest (http://127.0.0.1:8801/beaker/vendor/bower_components/angular/angular.js:7991:7)
    at XMLHttpRequest.xhr.onreadystatechange (http://127.0.0.1:8801/beaker/vendor/bower_components/angular/angular.js:7947:11)

**Comment by samccone** [comment]
weird ha, looking into it

**Comment by samccone** [comment]
ok all fixed,

> Dear Epic Editor, I am not a fan

**Comment by scottdraves** [comment]
progress....  now i get

```
Uncaught TypeError: Cannot read property 'documentElement' of null 
```

when i open the following

```
http://atwallab.cshl.edu/teaching/QBbootcamp3.ipynb
```

**Comment by samccone** [comment]
ok so with large notebooks this seems to happen

**Comment by scottdraves** [comment]
if i load this notebook, the markdown cells can't be edited
http://nbviewer.ipython.org/github/amplab/datascience-sp14/blob/master/hw2/HW2.ipynb

also, the reload/stop button and the favicon flicker horribly during import.
did import go south in general?

**Comment by anglee** [comment]
With 4e2c42d, I am still able to reproduce the moving up resulting in blank markdown issue. @samccone Did you lose the fix somehow when rebasing?

**Comment by anglee** [comment]
Looks like the ipynb blank markdown issue doesn't always happen. Actually it has nothing to do with ipynb. It seems depends on what's in the markdown (no matter if it is from a ipynb notebook). And when that happens, reloading the page seems to fix the issue. Here is an example notebook: https://gist.github.com/anglee/d36c3e27e6601b503794

**Comment by samccone** [comment]
alright this "works" for me other than in that ipython notebook you gave me @scottdraves , however that ipython notebook actually disconnects my client when I load it.

**Comment by anglee** [comment]
Thanks @samccone. I found some strange issues after pulling your latest change:
1. create a Empty Notebook
2. add a markdown cell
3. type "A" in it
4. add another markdown cell immediately after the first one
the first one went blank
That's a strange issue.
And then,
5. type something in the second markdown cell
6. Move it up
7. Now both show content ok
But,
8. click in the second cell (that now has "A"), note it is the first cell that entered edit mode.

**Comment by samccone** [comment]
Alright this is going to take a new approach since today has been pretty bit or miss with this issue

**Comment by samccone** [comment]
~~closing in favor of #642~~

**Comment by samccone** [comment]
Ok this has been updated with @anglee 's work, 

thanks again

**Comment by samccone** [comment]
awesome @scottdraves looks like it it is all working on my system, I do not have that ipython file from before, but everything else seems to be working for me here

**Comment by samccone** [comment]
just checked with the file

:green_apple:

**Comment by scottdraves** [comment]
:dolphin:

**Comment by samccone** [comment]
:ocean: :ocean:

**Pull request merged**
