### PR TITLE
Prevent modal screen overflow

### LINKED ISSUE #288: file save dialog can go off the bottom of the window
If you open a folder with a lot of subfolders or if you just make your window short, the bottom of the dialog, including the Open/Canel buttons goes off the bottom of the window and becomes inaccessible.

### PR DESCRIPTION
**Pull request by samccone**
Fixes #288

### CODE REVIEW

**Comment by anglee** [comment]
the 2 vertical scroll bars seems not desirable. We should always show the header and footer
image

**Comment by samccone** [comment]
hmm ok I will investigate a better fix

**Comment by samccone** [comment]
ok @anglee @scottdraves resolved it with the other solution :)

**Comment by samccone** [comment]
This seems to be working fine for me

**Comment by samccone** [comment]
esh we should revert this for now... it actually does not cover all the cases and causes bugs as @scottdraves pointed out

**Pull request merged**
