### PR TITLE
#6064 fix setting the Textarea width and height

### PR DESCRIPTION
**Pull request by MariuszJurowicz**

### CODE REVIEW

**Comment by MariuszJurowicz** [comment]
@scottdraves maybe we need the python `TextareaWidget` to be updated as well?

**Comment by scottdraves** [comment]
i am not seeing the right width for the TextArea and the TextField:
screen shot 2017-10-04 at 9 54 58 am

**Comment by scottdraves** [comment]
also please bring up to date with master.

**Comment by scottdraves** [comment]
actually the text field width seems broken on master as well

**Comment by scottdraves** [comment]
added https://github.com/twosigma/beakerx/issues/6080
and https://github.com/twosigma/beakerx/issues/6079

**Pull request merged**
