### PR TITLE
Add header menu spacing for markdown cells

### LINKED ISSUE #449: cell button menu aligned too low
there is whitespace above it, and it runs into stuff below it.  should be moved up.

screen shot 2014-08-12 at 11 19 31 am

### PR DESCRIPTION
**Pull request by samccone**
fixes #449

### CODE REVIEW

**Comment by anglee** [comment]
In the comment of #449, you were saying this is happening on a html (code) cell. The commit is about markdown. When I checkout the code and opened the tutorial notebook, I still see the same behavior to the first code cell (html cell with input cell hidden).

**Comment by samccone** [comment]
@anglee did you just checkout the branch and not run build?

**Comment by anglee** [comment]
I did run build. I guess what I was saying is I thought the problem is about the hidden input cells, but the class you changed looks like is for div in bk-markdown-cell.
pasted_image_8_14_14__4_07_pm

**Comment by samccone** [comment]
ah ah you are right, shall get this one resolved :+1:  should be simple

**Comment by samccone** [comment]
cool thanks for the :eyes:  @anglee  all updated

**Pull request merged**
