### PR TITLE
refine hierarchy styles

### PR DESCRIPTION
**Pull request by samccone**
I think this is a huge improvement over what we currently have. More things are correctly aligned, there is better proximity between elements (making the need for more connecting lines a bit pointless), and overall less wasted spacing

What do you guys think :question: 
### Before

screen shot 2015-08-05 at 2 23 45 pm
### After

screen shot 2015-08-05 at 2 28 26 pm

### CODE REVIEW

**Comment by grin** [comment]
:+1:  to the "after" version...feels much more natural, shows the hierarchy well and doesn't waste so much space

**Comment by ildipo** [comment]
I agree - 'after' is much better

**Comment by DiegoAlbertoTorres** [comment]
Agreed! Also gray > blue

**Comment by scottdraves** [comment]
yup a big improvement.  i liked the thicker blue lines too, same thickness as the line "+" of the section toggle.  and change the section box to blue to match.

plus a horizontal line between section levels.

**Comment by samccone** [comment]
screen shot 2015-08-05 at 4 08 34 pm

**Comment by scottdraves** [comment]
can you try this please: 
screen shot 2015-08-05 at 1

**Comment by samccone** [comment]
yep it is  in progress :)

**Comment by samccone** [comment]
screen shot 2015-08-06 at 11 35 16 am

**Comment by scottdraves** [comment]
line should have same H position as the vertical line in the + of the section toggle
screen shot 2015-08-06 at 11 39 48 am

**Comment by scottdraves** [comment]
1) the top-level line is missing
2) there is a gap:
screen shot 2015-08-06 at 11 45 39 am

**Comment by scottdraves** [comment]
this is close now.  2 remaining problems
1) the gap above the + is larger than the gap below.
screen shot 2015-08-06 at 4 43 43 pm
they should both be small like the below gap.

2) remove the extraneous dead-end lines.  The main tut should look like:
screen shot 2015-08-06 at 4
instead of what it is now:
screen shot 2015-08-06 at 4 45 55 pm

**Pull request merged**
