### PR TITLE
PR for issue #4536 "update to d3 to 4.x"

### PR DESCRIPTION
**Pull request by konstantinTarletski**

### CODE REVIEW

**Comment by scottdraves** [comment]
The D3 tutorial looks good but all the native plots are blank and I see many JS console errors starting with:

```
beakerVendor.js:63042 TypeError: Cannot read property 'zoom' of undefined
    at Scope.scope.init (http://127.0.0.1:8801/5e2379f/beaker/app/dist/beakerOutputDisplay.js:15922:38)
```

to reproduce, open the notebook config/tutorials/plot-features.bkr

**Comment by sluhtoja** [comment]
kick jenkins

**Comment by scottdraves** [comment]
this is looking good!

however, zooming out works only if i turn the mouse wheel very slowly.
if i move it fast, then i only get one "tick" of zoom, instead of many.

**Comment by scottdraves** [comment]
cool thx zoom works well.  when i pan though, it works OK as long as I do it gently, but if i really shake the mouse, somehow the panning ends and it stops moving.

**Comment by scottdraves** [comment]
still it seems zooming and and out causes the plot to jump around.

**Comment by scottdraves** [comment]
zooming looks good now, thanks! 🐬 

a remaining problem:
* open file:config/tutorials/chartingTutorial.bkr
* scroll down to 1st chart
* in the legend, hover mouse over "3 month"

result: nothing happens
expected result: the blue line (for 3 month) becomes thick

**Comment by scottdraves** [comment]
👍 
cool now afaik remaining are:
* treemaps
* jenkins

**Pull request merged**
