### PR TITLE
plot colors should depend on theme #3173

### PR DESCRIPTION
**Pull request by mnavasiolava**
default plot colors depend on app theme.
theme object ({name: "", plotColors:[]}) was exposed to beaker object

### CODE REVIEW

**Comment by scottdraves** [comment]
this is good but is it possible to do better?
the problem is if you change the theme, you have to rerun the cells to get the colors to match.
in particular, on the publication server, running cells is not possible....

**Comment by mnavasiolava** [comment]
if color is not set to plot item (used one of the default theme colors) you shouldn't rerun the cell - new color will be applied automatically to plot after you change the theme
if color is set via beaker object i'm not sure that there is a way to update color without cell rerun, because plot model just contains color and it doesn't know that this color was taken from beaker object

**Comment by scottdraves** [comment]
i thought so... but then i did a careful check of the legend and it looks like just that part is not updated.
the main timeseries are.  i am using the SimpleTimePlot example from the beginning of the interactive charts tutorial.  in default theme, i render, take a snapshot of the legend, then switch to ambiance and then take another snapshot, the color in the legend is unchanged.  the lines did get brighter though:
screen shot 2015-12-29 at 7 35 07 pm
screen shot 2015-12-29 at 7 35 14 pm
screen shot 2015-12-29 at 7 35 37 pm

**Comment by mnavasiolava** [comment]
you're right, legend's colors are cached in state, i'll fix them

**Comment by scottdraves** [comment]
:+1:

**Pull request merged**
